cassandra/cqltypes.py, cassandra/metadata.py, tests/integration/standard/test_metadata.py
=> Schema metadata: use column names from composite types, exclude CQL-incompatible tables from export

cassandra/pool.py
PYTHON-195
Fixes a problem where connection.in_flight count leaks when keyspace
changes due to session.set_keyspace or 'USE' statements.
=> PYTHON-195 - Return connection to pool after set keyspace

cassandra/cqltypes.py
When the schema contains user defined types, binascii.uhexlify gets called.
In Python 3 unhexlify accepts "only bytestring or bytearray objects as input"
and returns bytes too. This caused apply_parameters to crash.
Now for Python 3 there'a a wrapper than accepts str or bytes and returns str.
=> Properly handle unhexlify argument type and return type in Python 3

cassandra/cluster.py
A small typo fix for `set_max_connections_per_host`'s docstring.
=> Fixed docstring typo

cassandra/cqltypes.py, cassandra/protocol.py, tests/integration/standard/test_types.py, tests/unit/test_marshalling.py, tests/unit/test_types.py
=> Support new 'date' and 'time' types in Cassandra

cassandra/cqltypes.py, cassandra/encoder.py, cassandra/protocol.py, cassandra/util.py, tests/integration/standard/test_types.py, tests/unit/test_marshalling.py, tests/unit/test_orderedmap.py, tests/unit/test_types.py
Superset of https://github.com/datastax/python-driver/pull/241
Updated to map native types to cql types.
The integration test will probably not be merged until we find out what versions of C* will have these types to test against.
I had some general difficulty testing against this branch due to some apparently unrelated server-side errors.
https://github.com/josh-mckenzie/cassandra/compare/7523_squashed
=> PYTHON-190 Updated date/time support

tests/integration/standard/test_udts.py
Collection datatypes are allowed inside UDT's as the UDT itself is frozen, which freezes the collections inside. This is true for all collection types except for Tuple, which must be declared as frozen<> explicitly.
=> enable collections inside UDTs via freezing Tuple

cassandra/cqltypes.py, cassandra/util.py, tests/unit/test_marshalling.py, tests/unit/test_policies.py, tests/unit/test_types.py
Original problem statement in https://datastax-oss.atlassian.net/browse/PYTHON-231.
This change uses the internal cassandra type (when materializing a map from native protocol) to serialize map keys for the OrderedMap index.
Some notes about how I arrived here:
- JSON serialization had okay performance, but not very good support for serializing arbitrary types, and even some built-in types (set, for example)
- I looked at using cassandra.encoder.Encoder to serialize keys as CQL literals
-- Performance with quoting was not great, and removing quoting/escapes would lead to ambiguous serialized form for collections
-- This introduced a cyclic dependency Encoder-->util.OrderedMap-->Encoder that was awkward to extract
- Using the cassandra type
-- Makes materializing the index on protocol …
=> PYTHON-231 - Normalized string encoding for OrderedMap Indexing

docs/cqlengine/upgrade_guide.rst
Just noticed a little typo in upgrade guide. Took the opportunity to add another commit to strip trailing spaces.
FYI, I already signed the contributor agreement when CQLengine (for which I already contributed some code) was moved into the Python driver.
=> Typo in CQLengine upgrade guide.

tests/integration/standard/test_authentication.py, tests/integration/standard/test_metadata.py, tests/integration/standard/test_metrics.py, tests/integration/standard/test_types.py
Some extra fixes to stabilize older C* versions.
=> Stabilize Jenkins on Cassandra 1.2 - 2.0

tests/integration/long/test_consistency.py, tests/integration/long/utils.py
Catch OperationTimedOut in consistency tests, sleep 1 second in while loops to save CPU cycles.
=> catch OperationTimedOut in consistency tests

tests/integration/long/test_schema.py
Handle OperationTimedOut in SchemaTests when dropping the keyspace.
=> Handle OperationTimedOut in SchemaTests

tox.ini
For some reason the new version of sure, cannot be installed by tox when specified as a dependency. Poking around I was able to determine this problem seemed to be introduced in 1.2.4, specifying version 1.2.3 seems to solve the problem for us.
=> Changes the version of sure, so it can be successfully installed.

tests/integration/standard/test_metadata.py
Temporarily synchronously refresh the schema metadata, until CASSANDRA-9391 is merged in so that the test passes with current C* versions.
=> Temporarily synchronously refresh the schema metadata, for IndexMapTests

cassandra/cqltypes.py, cassandra/protocol.py, tests/integration/datatype_utils.py, tests/unit/test_marshalling.py, tests/unit/test_types.py
CASSANDRA-8951 add support on the server side for tinyint and smallint types. This patch add support on the driver side.
=> Add support for tinyint and smallint types

cassandra/cluster.py, docs/api/cassandra/cluster.rst
PYTHON-291
Use Cluster.refresh_*_metadata instead
=> PYTHON-291 - Deprecate Cluster.refresh_schema and submit_refresh_schema

cassandra/cqlengine/columns.py, cassandra/cqltypes.py, cassandra/protocol.py
Whilst adding small and tiny ints to cqlsh I noticed that the DESCRIBE command was wrong, the column name was 'org.apache.cassandra.db.marshal.ByteType' instead of 'tinyint' and  'org.apache.cassandra.db.marshal.ShortType' instead of 'smallint'. I think the names of the types in cqltypes.py must match the names in org.apache.cassandra.db.marshal, see lookup_casstype_simple(). Therefore I changed them accordingly.
I also added the columns, but I did not test them.
=> Suggestions for PYTHON-295

cassandra/cluster.py
PYTHON-244
Fixes an issue where gevent is chosen based on module loaded, not monkey
patching.
In some debuggers, (PyCharm, for example), this would cause connecting
to timeout because gevent reactor is used without monkey patching.
=> PYTHON-244 - For DefaultConnection, default to gevent only if actually patched.

cassandra/policies.py
Found some issues with this reconnect policy:
```
class ConstantReconnectionPolicy(ReconnectionPolicy):
"""
A :class:`.ReconnectionPolicy` subclass which sleeps for a fixed delay
inbetween each reconnection attempt.
"""
def __init__(self, delay, max_attempts=64):
"""
`delay` should be a floating point number of seconds to wait inbetween
each attempt.
`max_attempts` should be a total number of attempts to be made before
giving up, or :const:`None` to continue reconnection attempts forever.
The default is 64.
"""
if delay < 0:
raise ValueError("delay must not be negative")
if max_attempts < 0:
raise ValueError("max_attempts must not be negative")
self.delay = delay
self.max_attempts = max_attempts
def new_schedule(self):
return repeat(self.delay, self.max_attempts)
```
If passing …
=> Check if max_attempts is None for ConstantReconnectionPolicy

cassandra/cqlengine/columns.py, cassandra/cqltypes.py, cassandra/encoder.py, cassandra/util.py, docs/api/cassandra/cqlengine/columns.rst, tests/integration/cqlengine/columns/test_validation.py, tests/integration/cqlengine/columns/test_value_io.py, tests/integration/cqlengine/model/test_model_io.py, tests/integration/cqlengine/model/test_udts.py
Posting before fixing tests to get reviewer input.
=> PYTHON-245 - cqle: introduce 'date' and 'time' column types

tests/integration/cqlengine/columns/test_validation.py, tests/integration/cqlengine/columns/test_value_io.py, tests/integration/cqlengine/model/test_model_io.py, tests/integration/cqlengine/model/test_udts.py
Fixed cqlengine tests related to protocol v4 datatypes that were failing due to not being skipped properly.
=> Fix failing cqlengine tests related to protocol v4 datatypes

tests/integration/cqlengine/model/test_model_io.py
Change overlapping table names in cqle test v4 test test_model_io.py:TestModelIO.test_can_insert_model_with_all_protocol_v4_column_types
=> Change overlapping table names in cqle test v4 test

cassandra/cqlengine/columns.py, tests/integration/cqlengine/columns/test_validation.py
Systems like iOS creates uuid in uppercase, while storing to
cassandra one has to convert to lowercase before storing in cassandra.
This is quite difficult for developer to remember, it is better
handle at driver level.
=> Add support for upper case uuid

cassandra/murmur3.c
Fixes an issue where the hash value was cast to a four-byte type on some
platforms.
=> PYTHON-331 - Change return conversion for murmur3 ext

cassandra/cluster.py, cassandra/cqlengine/columns.py
Deprecates cqle TimeUUID.from_datetime, avoiding a rounding issue that manifested in Windows.
PR also includes a tweak to the default LBP, avoiding TokenAware when the murmur3 extension is not available.
=> PYTHON-341 - use common uuid_from_time function

README.rst, cassandra/cqlengine/columns.py, cassandra/cqlengine/functions.py, cassandra/cqlengine/management.py, cassandra/cqlengine/models.py, cassandra/cqlengine/named.py, cassandra/cqlengine/operators.py, cassandra/cqlengine/query.py, cassandra/cqlengine/statements.py, cassandra/cqlengine/usertype.py
Here it comes the backport I already did for the standalone cqlengine fork, now adapted to python driver one.
I have tested this one with a Cassandra 2.1 deployment and it worked fine. Integration tests are pending to be backported as well (they use the '{}'.format() syntax and probably more 2.7 idioms).
=> PYTHON-288  cqlengine 2.6 compatibility

cassandra/cluster.py, tests/integration/standard/test_cluster.py
Fixes an issue where connect will stall when connecting to mixed version
clusters.
Should not affect model consistency since we are already registered for
schema_change events.
=> PYTHON-303 - Don't wait for schema agreement during startup.

cassandra/cqlengine/connection.py
Sets the default keyspace for cqlengine models when passing in an existing session to `cqlengine.connection.set_session()`. Without this, the user will see an error when trying to perform Cassandra interactions with a Model instance like "Keyspace none does not exist" unless they explicitly set `models.DEFAULT_KEYSPACE` themselves ahead of time.
=> Set models.DEFAULT_KEYSPACE when calling set_session()

cassandra/metadata.py, tests/integration/standard/test_metadata.py
Fixes an issue where table meta export would contain min/max_threshold
settings, even for compaction strategies that do not accept those.
Resulting CQL would cause "ConfigurationException ... code=2300 ...
Properties specified [min_threshold, max_threshold] are not
understood by [some compaction strategy]"
=> PYTHON-352 - For meta export, don't copy in default min/max compaction thresholds

cassandra/metadata.py, tests/integration/standard/test_metadata.py
If there are not any clustering columns, a COMPACT STORAGE table can have any number of non-PRIMARY KEY columns and still be CQL-compatible.
See: [CASSANDRA-9647](https://issues.apache.org/jira/browse/CASSANDRA-9647)
Done for [PYTHON-360](https://datastax-oss.atlassian.net/browse/PYTHON-360)
=> Fix check for CQL compatibility of COMPACT STORAGE tables

cassandra/concurrent.py
Avoids materializing entire sequence before/after execution.
=> PYTHON-123 - Generator inputs/outputs for execute_concurrent

cassandra/policies.py, tests/unit/test_policies.py
DowngradingConsistencyRetryPolicy was ignoring write timeouts for
WriteTypes SIMPLE, BATCH and COUNTER even if responses received
was equal to 0.
It is valid to ignore the failure only if at least one response was
received.
=> Write timeouts being ignored with 0 responses

tests/integration/standard/test_control_connection.py, tests/integration/standard/test_metadata.py
Our control connection test should not run against anything with protocol level 3, as UDT will not be supported.
Updated our Metadata tests to correction check for explicitly defined thresholds on compaction strategies.
=> Fixing a few minor bugs in our tests for 2.7 release

cassandra/connection.py, cassandra/io/twistedreactor.py, tests/integration/standard/test_connection.py
=> PYTHON-381 - Use connect_timeout for socket connect in addition to negotiation

docs/query_paging.rst
But I imagine paging is also enabled when for protocol version 4?
=> The default protocol version seems to be 4, not 2

setup.py
Python3 ships with concurrent.futures so it shouldn't be pulled in but with latest concurrent.futures release on pypi they broke py3 compatibility:
https://github.com/agronholm/pythonfutures/issues/41
=> Futures from pypi isn't py3 compatible

test-requirements.txt
Adding gevent, and eventlet requirements to the test-requirements.txt. We have unit tests that require them to run, and I think it's fair to require them for validation purposes.
=> PYTHON-397 Adding requirements for gevent and eventlet in test.

setup.py
This version required for closures in cdefs in cython_marshal.pyx
see PYTHON-396
=> PYTHON-396 - Require Cython 0.21+ for build

tests/unit/cython/utils.py
Fixes an issue where some module builds were being attempted at load
time. This was a problem for cassandra/numpy_parser, which requires a
header file not necessarily on the inlucde search path.
=>  PYTHON-398 - Only have pyximport installed while importing test modules

tests/integration/cqlengine/query/test_named.py
This scenario has already be covered traditionally in test_query.py. This tests basically the same functionality using clqengine.
=> Added tests for PYTHON-406. NamedTable tests with materialized views.

cassandra/cluster.py, cassandra/query.py
`bind_params` raises `UnicodeDecodeError` if query is unicode. Since `bind_params` is used by `Cluster.execute` and `BatchStatement.add` it is better to move type checking of query inside `bind_params`.
=> fix unicode encoding issue for query.bind_params

cassandra/query.py
Currently it throws an exception because we are trying to get the 0th element, but if there are no results we should just say the trace isn't yet incomplete.
This can occur when the tracing stage is backed up and the response is sent before the session has been persisted.
=> Handle case where query trace returns nothing

cassandra/cqlengine/columns.py, cassandra/cqlengine/models.py, cassandra/cqlengine/usertype.py, tests/integration/cqlengine/model/test_model_io.py
The first unit-test (`test_previous_value_tracking_of_persisted_instance`) pass and the internal state of column's previous value and changed columns are properly tracked. The second (`test_previous_value_tracking_on_instanciation`), which run a scenario similar to the first, fail.
The difference ? The first test starts with a CQLengine instance that is already persisted to Cassandra (thanks to the use of `.create()`). The second test starts with an instance that hasn't been persisted yet.
I think we should change the way CQLengine operate on instantiation. So that both the internal `previous_value` property of each column and the object's `get_changed_columns()` method reflect the reality of an instance that is not yet persisted.
=> PYTHON-348 - Track previous value of columns at instantiation

cassandra/cluster.py, cassandra/obj_parser.pyx, cassandra/protocol.py
Fixes a not-well-understood issue that would cause segfualts when
building with Cython < 0.22
=> Don't reference cython genexp from core modules

cassandra/cqlengine/columns.py
In some cases the ``value`` attribute is ``None``, and without checking we are accessing a method assuming it's a valid object. This fix helps achieving the desired functionality/outcome for such cases without breaking the intended logic.
=> Fix: crash while working with UDTs

cassandra/cqlengine/columns.py, tests/integration/cqlengine/columns/test_validation.py
* Remove the DateType.deserialized() use since the mapper should not deal with serialized data
* Add DateTime tests for a timestamps and invalid inputs
=> PYTHON-354 - DateType.deserialize being called with one argument vs two

cassandra/cqlengine/models.py, tests/integration/cqlengine/model/test_model.py
Resolves AttributeError when trying to query without a keyspace name,
instead raising a CQLEngineException.
=> PYTHON-395 - cqle: guard against formatting an invalid keyspace in a query

cassandra/cython_utils.pyx, tests/integration/cqlengine/columns/test_validation.py, tests/unit/cython/test_types.py, tests/unit/cython/test_utils.py, tests/unit/cython/types_testhelper.pyx, tests/unit/cython/utils_testhelper.pyx, tests/unit/test_time_util.py, tests/unit/test_types.py
* Fix date overflow with large timestamp
* Add tests for DateType Cython deserializer
=> PYTHON-452 - Fix Cython deserializer date overflow with large timestamp

cassandra/connection.py
Add comparison operator to allow Timers with the same end time to be
pushed into heaps. It's poorly documented, but the warning can be found
here:
https://docs.python.org/2/library/heapq.html#priority-queue-implementation-notes
"In the future with Python 3, tuple comparison breaks for (priority,
task) pairs if the priorities are equal and the tasks do not have a
default comparison order."
=> Fix Python3 bug with Timers and heaps

cassandra/io/eventletreactor.py
The eventlet read loop runs select before each recv call. This will
fail because recv() on an ssl socket might read more data than
requested from the underlying socket in order to have enough context
for decryption. These extra bytes would be returned by the next recv
on the ssl socket, but are not known to underlying socket so select
will hang.
It is my understanding that eventlet implements blocking IO by using
poll under the hood and yielding, so the select should not be
necessary at all
=> Fix hang when using eventlet and ssl

cassandra/cqlengine/models.py, cassandra/cqlengine/usertype.py, cassandra/protocol.py, tests/integration/cqlengine/model/test_udts.py
Previously UDTs with different db_fields would not map properly, resulting in None for all fields
inserted or queried.
=> PYTHON-346 - cqle: allow db_field for fields in UDTs

cassandra/cqlengine/usertype.py, tests/integration/cqlengine/model/test_udts.py
This is a very small fix for [PYTHON-502](https://datastax-oss.atlassian.net/browse/PYTHON-502). 
Please let me know if the unit test I added to confirm the fix is not in the correct place.
=> Corrected incorrect reference to self._columns in UserType

cassandra/cqlengine/models.py, cassandra/cqlengine/query.py, tests/integration/cqlengine/columns/test_container_columns.py, tests/integration/cqlengine/management/test_compaction_settings.py, tests/integration/cqlengine/management/test_management.py, tests/integration/cqlengine/model/test_class_construction.py, tests/integration/cqlengine/query/test_queryset.py
also, a bonus fix for delete queries on models with composite partition keys
=> PYTHON-351 - fix various queries when using db_type on partition key column

cassandra/cqlengine/management.py, cassandra/cqlengine/models.py, docs/api/cassandra/cqlengine/models.rst, tests/integration/cqlengine/management/test_management.py, tests/integration/cqlengine/model/test_class_construction.py, tests/integration/cqlengine/model/test_model.py
=> PYTHON-337: case sensitive support for column family name

cassandra/cqlengine/columns.py
Fixes an issue where a model instance created with explicit None fields
would not persist as such on save()
PYTHON-475
=> cqle: show None values as deleted if the value is explicitly set

cassandra/cqlengine/connection.py
=> cqle: always set default keyspace from conn.set_session

tests/integration/cqlengine/management/test_management.py, tests/integration/cqlengine/model/test_class_construction.py, tests/integration/cqlengine/model/test_model.py
Formatting fixes, adding documentation.
Added skip to test_sync_index_case_sensitive until we can figure out why it's not working against C* 2.0
=> PYTHON-337 adding documentation to tests

cassandra/cluster.py
To make easier developing application working with several DCs we need to have `Cluster.default_serial_consistency_level` in addition to `Cluster.default_consistency_level`.
=> Added default_serial_consistency_level

cassandra/io/eventletreactor.py
It seems recent versions of eventlet (tested on 0.18.4) has changed
which exception is raised on timeout during recv(). This was not
handled properly by PR #485 which caused a regression.
=> Fix EventletConnection without ssl on recent versions of eventlet

tests/integration/cqlengine/columns/test_container_columns.py, tests/integration/cqlengine/connections/__init__.py, tests/integration/cqlengine/connections/test_connection.py
Fixing some bad test documentation, and adding integration test for PYTHON-486.
=> Adding integration test for PYTHON-486

tests/integration/cqlengine/connections/test_connection.py, tests/integration/cqlengine/management/test_compaction_settings.py, tests/integration/cqlengine/management/test_management.py, tests/integration/cqlengine/query/test_queryset.py, tests/integration/cqlengine/test_batch_query.py
TestCase for PYTHON-323.
Fix for test_connection.py so that it returns to the default keyspace.
Regex assertion fixes
=> PYTHON-323  Integration test for PYTHON-323  and other general test fixes

cassandra/cqlengine/management.py
Sync table fails on complex fields with index=True. It tries to create duplicate index. 
This happens because for complex field - index target look like "values(<column_name>)" instead of "<column_name>".  
Jira Issue: https://datastax-oss.atlassian.net/browse/PYTHON-533?jql=text%20~%20%22secondary%22
=> Fix for #Python-533. Secondary index on set field

cassandra/cqlengine/operators.py, cassandra/cqlengine/query.py, cassandra/cqlengine/statements.py
also fixes an issue where iff did not use the column's db_field
PYTHON-528
=> PYTHON-528 - cqle: support more comparisons in LWT conditional

tests/integration/cqlengine/__init__.py, tests/integration/cqlengine/query/test_batch_query.py, tests/integration/cqlengine/query/test_datetime_queries.py, tests/integration/cqlengine/query/test_named.py, tests/integration/cqlengine/query/test_queryoperators.py, tests/integration/cqlengine/query/test_queryset.py, tests/integration/cqlengine/query/test_updates.py
Also Updating some tests to add expected query counts.
There are more places we can annotate, such as table syncs and UDTS, but this is a decent enough start, and would have caught the error that spawned this issue.
=> PYTHNON-525. Adding decorator for counting underlying query execution

benchmarks/base.py, benchmarks/callback_full_pipeline.py, benchmarks/future_batches.py, benchmarks/future_full_pipeline.py, benchmarks/future_full_throttle.py
Add the read benchmark support. As well as the main addition, these features are now also available:
* Specify the keyspace name (-k)
* Keep the data after the benchmark (--keep-data)
* Specify the number of columns for the schema (-c)
* Specify the column type for the schema (--column-type)
* The benchmark now writes N partition keys rather than a single one
=> Benchmarks read

cassandra/deserializers.pyx, cassandra/numpy_parser.pyx, tests/integration/standard/utils.py
This PR addresses a bug in NumpyProtocolHandler to properly handle empty strings:
https://datastax-oss.atlassian.net/browse/PYTHON-550
It doesn't support NULL string values however, which requires more invasive changes (e.g. making use of NumPy's missing values support).
=> Support empty string values in NumpyProtocolHandler

docs/cqlengine/queryset.rst
* Cannot filter by primary_key only (in example, created 'id' and set as a 'partition_key')
* Updated import from 'cqlengine' to 'columns' and 'functions'
=> Updates to queryset docs

cassandra/metadata.py, tests/integration/standard/test_metadata.py, tests/unit/test_metadata.py
fixes UnicodeDecodeError when one value has non-ascii values
=> PYTHON-559 - normalize BytesToken values to binary type

cassandra/metadata.py, tests/unit/test_metadata.py
On Python 3.x, dict.values() returns a view object and not a list of the
values.
Updating the content of the original dict while iterating over the
values may raise a RuntimeError exception, which is the case in the
Cluster._refresh_node_list_and_token_map() method to remove discovered
hosts which are not part of the specified cluster contact points.
The bug doesn't happen using Python 2.x as dict.values() returns a new
list containing the values of the dictionary, without any other
reference to original dictionary object.
This fix forces the original Python 2.x behavior to be the same in
Python 3.x as well.
PYTHON-572
=> Don't modify the Metadatas' hosts structure while iterating over it

appveyor.yml, appveyor/appveyor.ps1, appveyor/run_test.ps1, tests/unit/test_concurrent.py
This contains all the scripts, and necessary yaml files to get our project building in the appveyor environment. 
It's currently configured to run unit tests against python3.4, and standard Integration tests against 2.7. 
Both against C* 3.0.5
It can also be configured to run long tests and different python/cassandra versions by toggling the values in the matrix portion of the yaml.
=> Initial Appveryor enablement

cassandra/cluster.py, docs/api/cassandra/cluster.rst, tests/integration/standard/test_control_connection.py
=> PYTHON-583: Add API to get the host metadata associated with the control connection node

cassandra/cluster.py
As discussed in the ticket, cqlsh won't start with Python 2.7.12.
=> Fix for CASSANDRA-11850

cassandra/cluster.py
I'm seeing quite a few errors in the test harness where we are iterating over the pool values while they are changing.
The errors look like this.
`
File "/home/jenkins/.pyenv/versions/3.4.3/lib/python3.4/site-packages/unittest2/case.py", line 67, in testPartExecutor
yield
File "/home/jenkins/.pyenv/versions/3.4.3/lib/python3.4/site-packages/unittest2/case.py", line 625, in run
testMethod()
File "/home/jenkins/workspace/datastax.python-driver.master/e86c5da2/tests/integration/standard/test_metadata.py", line 830, in test_export_keyspace_schema
cluster.shutdown()
File "/home/jenkins/workspace/datastax.python-driver.master/e86c5da2/cassandra/cluster.py", line 1204, in shutdown
session.shutdown()
File "/home/jenkins/workspace/datastax.python-driver.master/e86c5da2/cassandra/cluster.py", line …
=> Fix pool size changing during iteration

cassandra/cqlengine/query.py, tests/integration/cqlengine/test_lwt_conditional.py
Currently it is possible to issue an update with conditions that also makes those conditions impossible to satisfy for the subsequent DELETE statement for NULL columns. This patch removes any updated fields from the conditional statement before issuing the DELETE statement.
=> Avoid LWTExceptions when updating columns that are part of the condition

cassandra/cqlengine/query.py
I think the attribute referenced should be <code>partition_key</code>. I noticed this issue when I received an <code>AttributeError</code> upon trying to delete a row.
=> Correct typo in partition_key check

cassandra/cqlengine/models.py, cassandra/cqlengine/query.py, docs/api/cassandra/cqlengine/models.rst, docs/cqlengine/queryset.rst, tests/integration/cqlengine/test_ttl.py
__default_ttl__ will be deprecated in 4.0. We now relies on the cassandra default_time_to_live feature.
=> PYTHON-538: cqlengine deprecate Model.__default_ttl__

tests/integration/cqlengine/model/test_updates.py
This PR extends the initial no-op model update unit-tests to primary keys, as I expect the update operation to be skipped and ignored entirely if the value of the primary key hasn't changed a bit, mirroring the current behaviour on arbitrary columns.
I also added a new unit test section covering the same update operations trough the use of value assignation.
=> Extend no-op model update tests to primary keys

docs/getting_started.rst
I think there is a missing comma in one of the query code samples - have added it in.
=> Add missing comma to code sample

cassandra/connection.py, cassandra/io/eventletreactor.py, cassandra/io/geventreactor.py
removes the need for eventlet and gevent checking for timeouts
=> PYTHON-600 - make connection timeout infinite by default

cassandra/cqlengine/management.py, cassandra/cqlengine/query.py, tests/integration/cqlengine/test_context_query.py
* Add ContextQuery
* Add multiple keyspaces support to sync_table
* Add multiple keyspaces support to drop_table
missing doc...
=> PYTHON-598: Add ContextQuery to allow switching the model keyspace easily

cassandra/cqlengine/columns.py, tests/integration/cqlengine/columns/test_validation.py
This PR:
* Add full unit-tests of CQLengine's `Ascii` columns.
* Extend `Text` columns unit-tests for minimal and maximal length.
* Thoroughly cover edge-cases on empty / blank / `None` value strings handling, especially in relation to the `required` column parameter.
* Align `Ascii` column behaviour to `Text`, by adding `min_length` and `max_length` parameter support.
=> PYTHON-609: Align Text and Ascii columns behaviour

cassandra/cqlengine/models.py, tests/integration/cqlengine/model/test_class_construction.py, tests/integration/cqlengine/model/test_model_io.py
I just stumbled upon an inconsistency regarding the way `get_changed_columns()` reports columns whose values have been updated.
`get_changed_columns()` in itself works fine. The heavy lifting has been implemented a year ago through #373 and #348, and is upstream since the early days of v3.0.0.
But if the behaviour of [`get_changed_columns()` is thoroughly covered by unit-tests](https://github.com/datastax/python-driver/commit/17f2bc13c2fda731e9de8217790730b151f962ec), there's an edge case when an instance hasn't been persisted yet. This issue only concerns unset columns with a default value.
This issue is demonstrated in the unit-tests attached to this PR. The fix consists in setting the default value of a column right away at instantiation if no value has been provided by the user.
On my …
=> [CQLengine] Set default value of columns on instantiation

cassandra/cqlengine/columns.py
restore hashability to Column in Python 3.x
=> PYTHON-618 - add hash function to cqlengine.columns.Column

cassandra/cluster.py
Whilst waiting for [PYTHON-651](https://github.com/datastax/python-driver/pull/665) to deliver a complete fix, I would like to merge this into cassandra-test to make sure it doesn't get forgotten in case we need to rebundle a new driver version before 651 is available, see [CASSANDRA-12736](https://issues.apache.org/jira/browse/CASSANDRA-12736) for more details.
=> Temporary fix for PYTHON-651

cassandra/cluster.py, cassandra/protocol.py, cassandra/row_parser.pyx, tests/unit/test_concurrent.py, tests/unit/test_response_future.py
As discussed in [CASSANDRA-11534](https://issues.apache.org/jira/browse/CASSANDRA-11534), we need CQL types in the result set in order to reliably format results with column aliases.
=> Added cql types to result set for CASSANDRA-11534

cassandra/cluster.py
We were having some trouble reconnecting to the cluster after all nodes went down. During investigation, we found what looks like a big typo here.
=> Fixup attribute name on cluster reconnect

cassandra/protocol.py
This is the pull request for [CASSANDRA-12838](https://issues.apache.org/jira/browse/CASSANDRA-12838).
Please don't merge it into cassandra-test until CASSNDRA-12838 is committed, in fact is there a way to coordinate this so that we avoid having dtests fail?
=> Expand QUERY/EXECUTE/BATCH flags from [byte] to [int]

cassandra/cqlengine/query.py
Addresses [PYTHON-645](https://datastax-oss.atlassian.net/browse/PYTHON-645).
I've tested locally with `python setup.py doc`, which no longer prints these warnings:
```/home/mambocab/cstar_src/python-driver/cassandra/cqlengine/query.py:docstring of cassandra.cqlengine.query.ContextQuery:4: WARNING: Inline emphasis start-string without end-string.
/home/mambocab/cstar_src/python-driver/cassandra/cqlengine/query.py:docstring of cassandra.cqlengine.query.ContextQuery:5: WARNING: Inline strong start-string without end-string.
```
I also viewed the docs locally with `python -m SimpleServer` and they look like I expect:
=> escape literal asterisks in docstring

cassandra/cqlengine/connection.py, docs/cqlengine/connections.rst, tests/integration/cqlengine/test_connections.py, tests/unit/cqlengine/test_connection.py, tests/unit/cqlengine/test_udt.py
I don't necessarily expect this to get merged as-is; this is more of a review request. I want to check:
- that others like the `for user_type, conn in product(set(udts), connection._connections.values())` approach
- that the tests in `tests/integration/cqlengine/model/test_udts.py` cover the cases we care about, in terms of ordering UDT definitions and connection creations. I think they have, but I'd like a review and to have another look myself.
=> PYTHON-649

cassandra/cluster.py, tests/integration/standard/test_cluster.py
Adds a test for PYTHON-669 and fixes the behavior it tests for.
=> PYTHON-669: Don't prepare queries on ignored hosts on_up

cassandra/query.py, tests/unit/test_query.py
A **len** method on BatchStatement would allow getting the length of the batch without poking around in the 'private' _statements_and_parameters field.
=> Add __len__ to BatchStatement

cassandra/cluster.py, tests/unit/test_cluster.py
First commit reverts part of the fix for [PYTHON-367](https://datastax-oss.atlassian.net/browse/PYTHON-367) (#379) that put `_start_timer` calls in code that could be called from secondary threads. This caused a race between timer cancellation and that `_start_timer` call.
The second commit adds a `_cancel_timer` call before defuncting connections if the `ResponseFuture` isn't going to retry the request. Commit message explaining this reproduced below:
>This allows us to revert some of the fix to PYTHON-367 without the timer
heap growing out of control as described on that ticket. We cancel
before defuncting to ensure that the timer doesn't hang around while
running callbacks. Between this change and the delegation of callbacks
to a secondary thread (see commit 5192302, part of the …
=> PYTHON-644 - Timer logic

setup.py
Adds a `CASS_DRIVER_ALLOWED_CYTHON_VERSION` "escape hatch" env var that allows users to specify what version of Cython to use.
You can verify this behavior by installing the driver in an environment without Cython installed, then opening the installed driver with
```
view `python -c 'from cassandra import cluster ; print cluster.__file__'`
```
and searching for `cython`. If you install without `CASS_DRIVER_ALLOWED_CYTHON_VERSION`, the driver is installed with `0.24.1`. If you install with `CASS_DRIVER_ALLOWED_CYTHON_VERSION=0.25.2`, the driver is installed with `0.25.2`. (This holds even when you've installed `Cython==0.25.2` in the environment you're installing the driver.)
=> let users specify Cython version

cassandra/cqlengine/models.py, docs/cqlengine/faq.rst, example_mapper.py
Add docs in relevant places for `None` semantics.
=> PYTHON-623, Document cqlengine None semantics

cassandra/cqlengine/connection.py, tests/integration/cqlengine/connections/test_connection.py
Turns out that allowing `hosts=None` is not only ok, but required for `connection.setup(hosts=None, ...)` and `connection.default` to continue working. This adds integration tests for those functions and fixes the regression.
I think maybe these integration tests could be unit tests, so don't merge just yet.
=> PYTHON-692, Allow hosts=None for register_connection

cassandra/cluster.py, cassandra/timestamps.py, docs/api/cassandra/cluster.rst, docs/api/cassandra/timestamps.rst, tests/unit/test_timestamps.py
Addresses PYTHON-676. The history isn't great, but I plan to squash before/on merge if there are no objections.
Unit and integration tests pass locally on py2.7. I have not tested this over actual timestamp discontinuities.
=> Timestamp generator

cassandra/metadata.py, cassandra/pool.py, cassandra/util.py, tests/unit/test_types.py
[PYTHON-714](https://datastax-oss.atlassian.net/browse/PYTHON-714)
This works because the decorated types implement `__eq__` and `__lt__` already.
We don't have to do the same for metadata.Token because it implements `__cmp__`
=> add total_ordering to Time, Date, & Host

cassandra/io/eventletreactor.py, cassandra/io/geventreactor.py
Addresses a bug (found by Jaume) in how the `EventletConnection` handles empty strings coming back from its socket.
=> Added fix for gevent and eventlet

cassandra/io/eventletreactor.py
This fixes the socket issue with eventlet. Apparently, there are some cleanup not properly done when the greenthread don't exist gracefully. This is an issue with evenlet+python2 only. It doesn't happen with python 3.
=> PYTHON-673: Ensure Evenlet greenthreads exit gracefully

tests/unit/test_cluster.py
```
These tests weren't failing on CI, because CI runs all the unit tests
together, and LibevConnection.initialize_reactor is called in the setup
for other tests, in particular tests.unit.io.test_libev{reactor,timer}.
```
@bjmb could you give this a quick review please?
=> initialize libevreactor for cluster unit tests

cassandra/cluster.py
PYTHON-733
Adam figured this one out -- if I understand correctly, there's a race between `add_callback`, which uses `_final_result` to determine if callbacks should be called or not, and `start_fetching_next_page`, which resets it.
Adam was able to deterministically trigger the hang by inserting a sleep here:
https://gist.github.com/bjmb/41999db20794dfbac91bff6264f032ff#file-poc_event-py-L54
which led to `start_fetching_next_page` being called before `add_callback`. With this modification, the script hangs consistently before the changes in this PR and successfully runs after it.
=> 733: race condition between start_fetching_next_page and add_callback

cassandra/cluster.py
> ERROR:cassandra.cluster:Error preparing query on all hosts: 
Traceback (most recent call last): 
File "cassandra/cluster.py", line 2230, in cassandra.cluster.Session.prepare (cassandra/cluster.c:38698) 
File "cassandra/cluster.py", line 2242, in cassandra.cluster.Session.prepare_on_all_hosts (cassandra/cluster.c:39022) 
RuntimeError: dictionary changed size during iteration
=> Fix RuntimeError caused by change dict size during iteration

cassandra/query.py
Make sure all trace mutations are written before considering a trace as complete.
=> PYTHON-730 Resulset.get_query_trace returns empty trace sometimes

cassandra/io/libevreactor.py, tests/unit/test_policies.py
[PYTHON-749](https://datastax-oss.atlassian.net/browse/PYTHON-749):
> There are a couple call sites for the `map` builtin that I believe weren't correctly converted for Python 3 -- they call `map` but don't consume the result. I... would like to see a test for the `LibevReactor` fail before we merge.
=> remove uses of map that don't work in py3

cassandra/policies.py, tests/unit/test_policies.py
This does a couple things.
- It changes the tests for `ExponentialReconnectionPolicy` to use `float`s instead of `int`s. This is the documented type to use. This also triggers the failures seen in #700.
- It changes the logic in `ExponentialReconnectionPolicy` to handle cases like those in the tests where `float`s can overflow.
Would love to hear from @vipjml (person who filed #700) if you have a moment to have a look and confirm this also addresses the issue.
=> fixes for ExponentialReconnectionPolicy

cassandra/cluster.py
@bjmb to review. Our fix for 755 makes us lose a race in setting `self._time_remaining`, but this change makes losing that not matter anymore.
=> 755 timeout error followup

CHANGELOG.rst, cassandra/cluster.py, cassandra/connection.py, docs/api/cassandra/cluster.rst, tests/unit/test_connection.py
Let's set a global timeout for *all* heartbeat futures rather than waiting one-by-one.
=> PYTHON-762: All Heartbeat futures should have the same timeout

CHANGELOG.rst, setup.py
The Windows compiler has the initialize method which is the one that raises an Exception when it doesn't find a valid C++ compiler.
=> Added a more complete pre build check to setup.py

CHANGELOG.rst, cassandra/connection.py
#784 should have been on a `python-*` branch to run the integration tests.
=> request_ids may not be returned to the pool (PYTHON-739) (replaces #784)

tests/integration/__init__.py
I had to jump through some hoops to keep a cluster around and examine `debug.log`. This simplifies that, adding a `KEEP_TEST_CLUSTER` env var.
@bjmb This is low-priority/non-urgent. When you get a chance, could you have a look?
=> KEEP_TEST_CLUSTER env var

CHANGELOG.rst, cassandra/policies.py, docs/api/cassandra/policies.rst, tests/integration/long/test_loadbalancingpolicies.py, tests/unit/test_policies.py
I need to write more documentation before we merge, but I wanted to get discussion going on API choices.
I chose to model the API here almost exactly off the [Java driver implementation](https://github.com/datastax/java-driver/blob/3.x/driver-core/src/main/java/com/datastax/driver/core/policies/HostFilterPolicy.java). The two relevant choices here:
- the predicate is immutable, and
- host-filtering takes place at policy-population time, not at query-planning time.
Does anyone have strong feelings either way about those? Changing either of these is totally doable, but would add more complexity and make the class harder to test.
=> Python host filter policy PYTHON-761

docs/upgrading.rst
I think this will help in cases like the one the user was confused about in [PYTHON-464](https://datastax-oss.atlassian.net/browse/PYTHON-464).
=> flesh out ResultSet upgrade guide (PYTHON-464)

docs/index.rst
Fixes a couple problems in the `index.rst`.
Once this is approved I'll port the Slack change to our older doc branches, and check that versions in other `index`es are correct.
=> fix docs/index.rst

cassandra/policies.py, tests/integration/long/test_failure_types.py, tests/integration/standard/test_cluster.py, tests/integration/standard/test_connection.py, tests/integration/standard/test_metrics.py
Replaced WhiteListRoundRobinPolicy for HostFilterPolicy + RoundRobinPolicy as part of replacing it. I've left the tests that actually test WhiteListRoundRobinPolicy until it's fully removed.
=> Replaced WhiteHost policy for FilterHost policy in tests

CHANGELOG.rst, cassandra/cluster.py, tests/integration/standard/test_cluster.py
This fixes the issue described in PYTHON-781, though I haven't been able to write an integration test to demonstrate this yet. Putting it up for high-level review first.
=> populate default lbp on connection (PYTHON-781)

CHANGELOG.rst, build.yaml, cassandra/__init__.py, cassandra/cluster.py, cassandra/protocol.py, tests/integration/__init__.py, tests/integration/standard/test_query.py, tests/unit/test_protocol.py, tests/unit/test_response_future.py
This deals with [PYTHON-678](https://datastax-oss.atlassian.net/browse/PYTHON-678)/[PYTHON-804](https://datastax-oss.atlassian.net/browse/PYTHON-804).
I honestly don't know what the user API looks like for this, so I don't have integration tests yet. I'll consult with folks tomorrow.
=> Change protocol to allow sending key space independent of query string (CASSANDRA-10145)

CHANGELOG.rst, cassandra/cluster.py
File "core/context.py", line 163, in shutdown
self.cluster.shutdown()
File "cassandra/cluster.py", line 1226, in cassandra.cluster.Cluster.shutdown (cassandra/cluster.c:18488)
for session in self.sessions:
File "python3.5/_weakrefset.py", line 60, in __iter__
for itemref in self.data:
RuntimeError: Set changed size during iteration
=> Fix RuntimeError on cluster shutdown

cassandra/cqlengine/columns.py
Current behaviour treats 0 as not specified at all. If this is not on purpose we should check for `None` explicitly instead to allow us to store empty strings in the database.
=> Allow min_length==0 for Column.Text fields

CHANGELOG.rst, cassandra/io/libevreactor.py
I'd rather do this solution than add a lock around [this part](https://github.com/datastax/python-driver/blob/d3e960134f97198f244873aa1ce66078947c3a89/cassandra/io/libevreactor.py#L97) and the part where the thread is joined. It looks more simple to me.
=> Lock joining the libev event loop thread

CHANGELOG.rst, cassandra/policies.py
[PYTHON-794](https://datastax-oss.atlassian.net/browse/PYTHON-794)
Had to do a little digging to find the writetypes, but I only found them in the documented cases. I can go dig the code back up if requested.
=> PYTHON-794: add VIEW and CDC writetypes

CHANGELOG.rst, cassandra/cluster.py, tests/unit/test_cluster.py
[PYTHON-812](https://datastax-oss.atlassian.net/browse/PYTHON-812)
I think this is the right way to implement this -- we check if `contact_points` is unset, not if it's the default value. That way, if a user has some weird configuration where they want to connect to `localhost`, but also want a non-default LBP, they should still be able to specify it.
=> WARN on Cluster.__init__ w contact points & no lbp

CHANGELOG.rst, cassandra/query.py
Before this patch all prepared statements would end up with
the default RetryPolicy.
=> PYTHON-861: query: make sure the retry_policy is passed to BoundStatements

CHANGELOG.rst, cassandra/cluster.py, tests/integration/simulacron/test_policies.py, tests/integration/standard/test_policies.py
This is a different solution https://github.com/datastax/python-driver/pull/873 and one that hopefully works better. The problem with the previous one was that for example if we are connected to one host cluster and the scheduled speculative execution happens before the regular attempt from the main thread (this is likely to happen since it's scheduled in `0` seconds). The `_query_plan` from `ResponseFuture` will have already been exhausted by the speculative executions and the attempt from the main thread will fail with `NoHostAvailable`.
In this PR `_on_speculative_execute` schedules itself again if the attempt from the main thread hasn't yet happened
=> Alternative solution for PYTHON-836

CHANGELOG.rst, cassandra/cluster.py
Tries to solve the same issue as #857.
I'm a little wary of adding a new place where `._timer` is set, but I think we're OK:
```python
def _on_speculative_execute(self):
self._timer = None
if not self._event.is_set():
if self._time_remaining is not None:
if self._time_remaining <= 0:
self._on_timeout()
return
self.send_request(error_no_hosts=False)
self._start_timer()
```
Here, if `_on_timeout` overwrites `._timer`, that's fine -- we know `._timer` is `None` anyway.
I was worried about deferring to the event loop and returning from `_on_timeout` without the work actually being done. However, _on_speculative_execute is only ever called from the event loop (see below) so I think it's ok to replace the timer and put the timeoout processing on the event loop, since nothing explicitly waits on …
=> PYTHON-853: delay timeout

CHANGELOG.rst, cassandra/cluster.py, tests/unit/test_resultset.py
=> PYTHON-947: Add one() function to the ResultSet API 

CHANGELOG.rst, cassandra/cluster.py, cassandra/query.py, docs/execution_profiles.rst, docs/faq.rst, docs/getting_started.rst, docs/upgrading.rst, docs/user_defined_types.rst, tests/integration/__init__.py, tests/integration/cqlengine/statements/test_base_statement.py, tests/integration/cqlengine/test_ttl.py, tests/integration/long/test_loadbalancingpolicies.py, tests/integration/standard/test_cluster.py, tests/integration/standard/test_concurrent.py, tests/integration/standard/test_custom_protocol_handler.py, tests/integration/standard/test_cython_protocol_handlers.py, tests/integration/standard/test_metadata.py, tests/integration/standard/test_prepared_statements.py, tests/integration/standard/test_query.py, tests/integration/standard/test_routing.py, tests/integration/standard/test_row_factories.py, tests/integration/standard/test_types.py, tests/integration/standard/test_udts.py, tests/unit/test_response_future.py, tests/unit/test_resultset.py
This is not the final PR, but wanted a review to be sure we agree on the changes.
* ResultSet doesn't have iteration support, neither `next()`. We need to create one with `iter(rs)` or in a loop as usual.
* A ResultSetIterator has been created to separate the logic from the ResultSet itself.
* Basic equality and indexing have been removed. It was present only for backward-compatibility and was one of the reasons of the bad design and mixed behaviors of the ResultSet  (a warning will be added in 3.14).
* Related to the point above, the *list_mode* has been removed. If the user need to materialize all results, he should use `list(rs)`
* Although this is not a common practice, if a second (or more) iterator is created.. it will continue to consume the data at the ResultSet state where the …
=> PYTHON-463 PYTHON-945 PYTHON-947: ResultSet refactoring

tests/unit/test_resultset.py
It's a dumb workaround, but it (I think) works. Not worth spending more time digging.
=> fix test_indexing_deprecation pre-3.0

CHANGELOG.rst, cassandra/cluster.py, cassandra/concurrent.py, cassandra/metrics.py, cassandra/util.py, docs/api/cassandra/cqlengine/columns.rst, docs/api/cassandra/protocol.rst, docs/cqlengine/batches.rst, docs/cqlengine/connections.rst, docs/cqlengine/faq.rst, docs/cqlengine/queryset.rst, docs/installation.rst, docs/object_mapper.rst
[PYTHON-868](https://datastax-oss.atlassian.net/browse/PYTHON-868): The most important bit here is the first commit, which documents how to work around/shorten/avoid long Cython compilation times. I've also removed a lot of indentation from parts of the docs where it's unnecessary -- I thought this would be necessary to fix some docs issues, but it turns out that's unrelated. However, I think that removing them is an improvement nonetheless, as it removes a bunch of meaningless `<blockquote>` blocks.
=> Document long compile

CHANGELOG.rst, cassandra/cqlengine/columns.py, cassandra/cqlengine/query.py, docs/api/cassandra/cqlengine/columns.rst, tests/integration/cqlengine/query/test_queryset.py, tests/integration/cqlengine/test_connections.py
This PR will require some DSE tests with a dse-search index.
=> PYTHON-966: Allow filter queries with fields that have an index managed outside of cqlengine

CHANGELOG.rst, cassandra/__init__.py, cassandra/policies.py, cassandra/protocol.py, tests/integration/simulacron/__init__.py, tests/integration/simulacron/test_cluster.py, tests/integration/simulacron/test_policies.py
Many changes just to add something an error message, but we were getting circular import errors if we leaved `WriteType` in policies
=> PYTHON-941 Improve error for batch WriteTimeouts

CHANGELOG.rst, cassandra/metadata.py, tests/integration/standard/test_metadata.py, tests/unit/test_metadata.py
According to Cassandra:
> A Range is responsible for the tokens between (left, right]. **
However, `TokenMap.get_replicas()` appears to implement [left, right).
This pull request aims to resolve this disagreement.
_** Source: https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/dht/Range.java_
=> Token range ownership

.travis.yml
Fixing the pypy tests, for 3.3 (see #953)
=> gevent: requires ares.h

CHANGELOG.rst, cassandra/cqlengine/query.py, cassandra/cqlengine/statements.py, tests/integration/cqlengine/query/test_updates.py, tests/integration/cqlengine/statements/test_assignment_clauses.py, tests/integration/cqlengine/statements/test_update_statement.py
This PR now let None pass along the UPDATE statements. Map key deletions is a bit different.. so some code has been preserve to avoid the creation of tombstone on every update.
=> PYTHON-506: Remove two-phase query when deleting values

CHANGELOG.rst, cassandra/io/libevreactor.py, tests/integration/standard/test_connection.py, tests/unit/io/test_libevreactor.py
This PR is very similar to https://github.com/datastax/python-driver/pull/941, so some of the review comments there might apply here as well @mambocab
=> PYTHON-973: Use global variable for libev loops so it can be subclassed

.travis.yml, README-dev.rst, README.rst, docs/index.rst, docs/installation.rst, setup.py, tox.ini
3.3 has been removed from Travis, and it could start running the tests on 3.7
=> tox: remove 3.3

CHANGELOG.rst, cassandra/query.py, tests/unit/test_row_factories.py
[PYTHON-893](https://datastax-oss.atlassian.net/browse/PYTHON-893).
As mentioned on that ticket, we've decided it's better to degrade to a pseudonamedtuple (with a warning) than to simply fail on very long lists of columns.
=> PYTHON-893: fallback implementation for namedtuple row factory

CHANGELOG.rst, tests/integration/standard/test_cluster.py
Addresses [PYTHON-998](https://datastax-oss.atlassian.net/browse/PYTHON-998). See commit message:
> The old behavior led to Session objects not being registered with the cluster, and thus not cleaned up on Cluster.shutdown().
=> Python fix keyspace test hang

CHANGELOG.rst, cassandra/metadata.py, tests/integration/standard/test_metadata.py
This requires some rebasing, but should be good to go.
Could you run the new metadata tests against `trunk` locally, @aboudreault? There are some failures when creating MVs, but I think that's ok for now.
=> Python 992 virtual keyspaces

CHANGELOG.rst, cassandra/io/asyncorereactor.py, cassandra/io/libevreactor.py, tests/unit/io/utils.py
Addresses [PYTHON-1024](https://datastax-oss.atlassian.net/browse/PYTHON-1024).
The new test for SSL error handling in the first commit is intended to fail on that commit -- Alan, could you check that it does?
I'm pretty confident that [removing this check from this test](https://github.com/datastax/python-driver/compare/long-python_catch-ssl-errs?expand=1#diff-b0e8d7ab6ad634ee6bddc3f68e7c013eL269) is fine. Could you poke through (in particular where `_current_frame` is used) and see if I'm missing anything?
=> PYTHON-1024: fix catch ssl err catching

CHANGELOG.rst, cassandra/encoder.py, cassandra/metadata.py, tests/unit/test_metadata.py
Adds a failing test, and then a fix, for [PYTHON-1008](https://datastax-oss.atlassian.net/browse/PYTHON-1008). I explained the bug in a commit message, reproduced below:
>The CREATE CUSTOM INDEX statement initially generated in
`IndexMetadata.as_cql_query` is always a `unicode` object under Python 2,
because they are derived from CQL `text` fields in in
`system_schema.indexes`, and we serialize the bytes we get from
`text`-type values with `.encode('utf-8')`.
>The result of `cql_encode_all_types` is always a `six.binary_type`, i.e.
a `str` under Python 2.
>Notably, Python 2 `str` objects cannot be cast to `unicode` objects if
they contain non-ASCII characters, including those used to encode
Unicode characters in UTF-8. These casting errors can occur during
attempts to concatenate these …
=> Python 1008

CHANGELOG.rst, cassandra/cqlengine/query.py
There are many resultset indexing use in tests. This is normal since all those fixes are in the 4.x branch. I did some attempts to ignore those warning when running tests without luck.
=> PYTHON-1015: Fix wrong resultset indexing use

CHANGELOG.rst, cassandra/__init__.py, cassandra/cluster.py, tests/integration/simulacron/__init__.py, tests/integration/simulacron/test_cluster.py
We can push this to the next release if timing necessitates it; I'm just PRing because I found this branch lying around.
=> Python 895 require only one resolved contact point

CHANGELOG.rst, cassandra/connection.py, tests/unit/test_connection.py
Supercedes #952 to fail fast if we import lz4 incorrectly.
=> PYTHON-1042: replacement for lz4 test

CHANGELOG.rst, cassandra/connection.py
The tests passed except for the `test-dse` tests. Test run 1 is the same code; the new force-pushed commit was just a commit message change.
You can verify that the feature works manually by connecting to a C* instance running `trunk` and checking `s.execute('SELECT * FROM system_views.clients'))`.
=> PYTHON-1068: send driver name/version in startup

CHANGELOG.rst, cassandra/io/asyncorereactor.py, cassandra/io/libevreactor.py, tests/integration/long/test_ssl.py
This is similar to the PYTHON-1024 fix. This PR improves how SSL WANT_READ/WANT_WRITE errors are handled. Basically, we just re-queue the chunk to complete the message instead of erroring the connection.
Note: The asyncio fix is not included in this PR.
=> PYTHON-891: Improve handling of ssl errors when sending a message

CHANGELOG.rst, cassandra/cqlengine/columns.py, cassandra/metadata.py, tests/integration/simulacron/test_empty_column.py
Not much to do in the python-driver about this, only a minor fix in cqlengine. All tests are based on the CSHARP ones.
=> PYTHON-1082: accept legacy empty as column names

CHANGELOG.rst, cassandra/policies.py, tests/unit/test_policies.py
@jorgebay I noticed when I was done implementing this feature that the nodejs impl does a bit more than the python and the Java ones. The nodeJS one applies only +0-15% when the delay is base_delay and only -0-15% when it's max delay. Do you think it's mandatory to modify?
=> PYTHON-1065: Add jitter to ExponentialReconnectionPolicy

cassandra/policies.py
Remove a sentence from the API docs pointing to `RoundRobinPolicy` as the default lbp.
=> Remove doc pointing RoundRobinPolicy as default

.travis.yml, test-requirements.txt, tox.ini
Enables 3.7-dev tests on travis
also removes PyYAML which is not used by anyone and fails on 3.7
=> tox: enable python 3.7

CHANGELOG.rst, cassandra/metadata.py, tests/integration/standard/test_metadata.py
https://datastax-oss.atlassian.net/browse/PYTHON-1100
I might have gone overboard with the tests, but I didn't find other tests around the compact storage flags, so figured it'd be good to add a couple other checks there too.
=> [PYTHON-1100] Fix incorrect metadata for compact counter tables

CHANGELOG.rst, cassandra/cluster.py, docs/api/cassandra/cluster.rst
https://datastax-oss.atlassian.net/browse/PYTHON-1119
from local build of docs:
=> [PYTHON-1119] Set the proper default ExecutionProfile.row_factory value

CHANGELOG.rst, cassandra/cqltypes.py, cassandra/metadata.py, tests/unit/test_metadata.py
https://datastax-oss.atlassian.net/browse/PYTHON-1031
Functions don't accept frozen as part of the type arguments even though the collections get frozen after creation. To properly return the CQL statement we need to strip frozen from the type we receive from the server.
=> [PYTHON-1031] Remove "frozen" from metadata of function arguments

CHANGELOG.rst, cassandra/cqlengine/connection.py
https://datastax-oss.atlassian.net/browse/PYTHON-1105
=> PYTHON-1105: Include param values in cqlengine logging

CHANGELOG.rst, cassandra/cqlengine/statements.py, tests/integration/cqlengine/test_timestamp.py
https://datastax-oss.atlassian.net/browse/PYTHON-1093
Continuation of #1018 (keeping the original commits) with an added integration test, some small code changes to make it consistent with the Update statement, and a rebase to keep the changelog current.
=> TTL and TIMESTAMP in cqlengine (round 2)

CHANGELOG.rst, cassandra/metadata.py
This update makes the `make_token_replica_map` function multiple times
faster. 
**Problem**
The previous implementation used a combination of islice and cycle.
`cycle` will build an internal list, and save every element it produces.
`islice` will iterate over everything in it's sequence up to `start`.
On every token in the ring, it will build the entire list of offsets again in memory up to that tokens index in the list. The `islice` and `cycle` combination was used to allow nice wrapping around of the list.
I've replaced this with a simple iteration over the existing list.
Timings on my (admittingly slow) machine for these tests show
differences in speed of:
pre_change:
test_nts_token_performance_large_cluster:
4.509002365055494
test_nts_token_performance_large_with_small_backup …
=> [PYTHON-622] Performance Improvement for NetworkTopologyStrategy make_token_replica_map

tests/integration/cqlengine/test_lwt_conditional.py, tests/integration/standard/test_query.py
We've seen some recent occasional test failures in LWT tests. In particular:
tests.integration.standard.test_query.LightweightTransactionTests.test_was_applied_batch_stmt
tests.integration.cqlengine.test_lwt_conditional.TestConditional.test_update_conditional_success
Since mixing LWT and non-LWT statements can cause problems, I added `if_not_exists()` to our cqlengine LWT tests to make the insert statements into LWTs.
In the failing batch test, I included a LWT in the failing batches, and modified the SELECT statements to use SERIAL consistency.
=> Fix flakiness in LWT tests

cassandra/cluster.py, test-requirements.txt, tests/__init__.py, tests/integration/simulacron/test_connection.py, tox.ini
This is part of the python 3.7 support for the next release. Unfortunately, the Eventlet reactor is not compatible with the built-in concurrent.futures.ThreadPoolExecutor. 
This Pull Request basically detects this situation and raise an error to the user. To use Python 3.7 and Eventlet, the user has to install an additional package, so we can use a custom thread pool made for it.
@aholmberg Can you do a quick review?
=> PYTHON-1016: Python 3.7 eventlet reactor fix

build.yaml, test-requirements.txt, tests/integration/simulacron/test_endpoint.py
Updated twisted dependency so windows install doesn't take 30 minutes. In testing the changes, also noticed a test failing for all twisted builds, so fixed the test as well.
Windows build:
https://ci.appveyor.com/project/DataStax/python-driver/builds/27114069
Jenkins build customized to use twisted:
https://jenkins-drivers.build.dsinternal.org/view/python-driver/job/datastax.python-driver.dev-python-1037-twisted.commit_branches_dev/
=> Fix twisted tests (PYTHON-1037)

CHANGELOG.rst, cassandra/cqlengine/connection.py, tests/integration/cqlengine/connections/test_connection.py, tests/unit/cqlengine/test_connection.py
Opening a new PR instead of #1033
https://datastax-oss.atlassian.net/browse/PYTHON-1009
=> [PYTHON-1009] Support execution profiles in cqlengine

CHANGELOG.rst, build.yaml, cassandra/cluster.py, tests/integration/__init__.py, tests/integration/simulacron/test_connection.py, tests/integration/upgrade/test_upgrade.py, tests/integration/util.py, tests/unit/test_response_future.py
This PR concerns https://datastax-oss.atlassian.net/projects/PYTHON/issues/PYTHON-1044
It contains a fix, unit and integration tests. I had some problems with integration test configs, so 
6ebe0d8 addresses this.
Lastly, I would like to mention that this issue is all about an edge case and therefore extremely difficult to reproduce. However, some microservices of our business software got stuck in production several times in the last few months due to this.
=> [Python 1044] Driver hangs/deadlock if all connections dropped by heartbeat whilst request in flight and request times out

CHANGELOG.rst, cassandra/cqlengine/columns.py, tests/integration/cqlengine/query/test_queryoperators.py
Python 2 returned lists for `.values()`. Python 3 returns view objects that aren't pickleable. This is the root of the error in PYTHON-1121.
=> [PYTHON-1121] Fix queryset generation for cqlengine Token instances

cassandra/cqlengine/columns.py
This fixes the previous link which is broken.
On a side note, maybe there should be `latest` docs website.
```
https://docs.datastax.com/en/dse/latest/cql/cql/cql_using/useMap.html
```
Should redirect to:
```
https://docs.datastax.com/en/6.7/latest/cql/cql/cql_using/useMap.html
```
And when the next version is released, latest should be updated, without updating links in the code.
=> Fix broken link to map type documentation

build.yaml
Python weekly jobs are also targeting PRs (with name master), for example:
- https://jenkins-drivers.build.dsinternal.org/view/python-driver/job/datastax.python-driver.PR.1009.weekly_async/
- https://jenkins-drivers.build.dsinternal.org/view/python-driver/job/datastax.python-driver.PR.1009.weekly_async/
=> Disable pull requests on weekly jobs

cassandra/cluster.py, cassandra/datastax/cloud/__init__.py, cassandra/io/twistedreactor.py, docs/cloud.rst, docs/security.rst, test-requirements.txt, tests/integration/advanced/cloud/test_cloud.py, tests/integration/long/test_ssl.py, tests/unit/io/test_twistedreactor.py
Might want to review the two commits separately.
Ran all tests (including long and cloud) using Twisted on a separate branch:
https://jenkins-drivers.build.dsinternal.org/job/riptano.python-driver.twisted-cloud.twisted_cloud/6/
The Unix socket test fails on twisted on master and this PR doesn't address that.
My reasoning behind the SSL context changes...
For the SSL verification, we need to:
1. Verify we have a valid certificate
2. Verify the hostname is correct
When we call `set_verify(VERIFY_PEER, callback)`, number 1 happens, but we still control what happens with the result:
> The return value of verify_callback controls the strategy of the further verification process. If verify_callback returns 0, the verification process is immediately stopped with "verification failed" state. If …
=> Twisted SSL context and cloud support

CHANGELOG.rst, cassandra/util.py, tests/unit/test_util_types.py
PYTHON-1172.
Need to be able to parse versions like: 4.0.0-alpha2-SNAPSHOT
=> Fix version parsing when two dashes in server version

CHANGELOG.rst, build.yaml, cassandra/cluster.py, cassandra/connection.py, cassandra/datastax/cloud/__init__.py, cassandra/io/eventletreactor.py, docs/cloud.rst, docs/security.rst, tests/integration/long/test_ssl.py
The reason for the instance checks in the eventlet code is that eventlet will monkeypatch the built in ssl module to use pyOpenSSL under the hood. We want to utilize that if we're relying strictly on ssl_options, but if we're passing an SSLContext, we must use the pyOpenSSL APIs.
=> [PYTHON-1162] Allow passing ssl context for Eventlet

cassandra/cqlengine/management.py
Instead a NameError will be thrown because unicode is unknown.
So I replaced unicode(exc) with six.text_type(exc) which will either use unicode or str.
=> re-raising the CQLEngineException will fail on Python 3

cassandra/__init__.py
There is a small typo in cassandra/__init__.py.
Should read version rather than versioni.
=> Fix simple typo: versioni -> version

cassandra/cluster.py, tests/integration/cqlengine/model/test_model.py
Move session id creation before insights reporter starts. When the insights reporter retrieves the startup data, it captures the session id. Since this runs in a separate thread, the session id is usually created by the time this capture actually runs. But it's a race, and sessionId can occassionally be captured as None.
Fix tests/integration/cqlengine/model/test_model.py:TestDeprecationWarning.test_deprecation_warnings: Asyncio throws warnings on python 2.7+ that aren't relevant to the test, so ignore them.
=> Changes from test failures

CHANGELOG.rst, README.rst, cassandra/cluster.py, cassandra/datastax/cloud/__init__.py, docs/cloud.rst, docs/index.rst
Just to verify, we DON'T plan on changing this particular flag or references to it?
https://github.com/datastax/python-driver/blob/master/cassandra/datastax/cloud/__init__.py#L44
=> PYTHON-1226 Remove all user-facing references to Apollo or Constellation

CHANGELOG.rst, cassandra/metadata.py, tests/unit/test_metadata.py
Converted replication factors from int's to strings to support the parsing of transient replications.
=> Python 1207 transient parsing

cassandra/metadata.py
Bug (reproducible in 3.11, 4.0):
```
cqlsh> CREATE KEYSPACE test1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'} AND durable_writes = true;
cqlsh> CREATE TABLE test1."default" (id text PRIMARY KEY, data text, etag text);
cqlsh> DESCRIBE TABLE test1.default ;
CREATE TABLE test1.default (
id text PRIMARY KEY,
data text,
etag text
) WITH additional_write_policy = '99p'
AND bloom_filter_fp_chance = 0.01
AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
AND comment = ''
AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
AND compression = {'chunk_length_in_kb': '16', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
AND crc_check_chance = 1.0
AND …
```
=> CASSANDRA-15663 Add 'default' to a list of reserved keywords

CHANGELOG.rst, build.yaml, cassandra/cluster.py, cassandra/connection.py, cassandra/metadata.py, cassandra/pool.py, cassandra/util.py, tests/integration/__init__.py, tests/integration/advanced/test_auth.py, tests/integration/simulacron/test_endpoint.py, tests/integration/standard/test_control_connection.py, tests/integration/standard/test_metadata.py, tests/integration/standard/test_single_interface.py, tests/unit/test_cluster.py, tests/unit/test_control_connection.py
This PR adds these features:
* The ability to specify a contact point as tuple: ('127.0.0.1', 9042) (so specifying the port by CP without having to create an explicit DefaultEndPoint. The main reason for this is that the OSS ccm (and Apple) is already using this. It was easy to support it anyway.
* system.peers_v2 support. I Implemented it the same way than the java-driver... we try to use it when we connect and initialize the control connection... otherwise we fallback to peers v1.
* With peersv2, ports are discovered per-host.
Next major: I want to be able to run the entire test suite using a single interface. e.g when testing C* 4.0+  (ticket to create). Too many changes were required at the moment since we use strings everywhere for node ip etc. and that would have been another mess …
=> PYTHON-700: Support port discovery for C* 4.0

CHANGELOG.rst, cassandra/metadata.py
This patch includes work discussed with @adelapena and @aboudreault in https://issues.apache.org/jira/browse/CASSANDRA-15663?focusedCommentId=17195546&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17195546. To complete [PYTHON-1269](https://datastax-oss.atlassian.net/browse/PYTHON-1269) I also removed `REPLACE` from the list of reserved keywords.
=> PYTHON-1269 Update list of CQL keywords

cassandra/query.py
Tracing code uses a deprecated mechanism for fetching the first row
when populating traces. The behavior is now fixed.
=> query: fix deprecation warning for tracing

cassandra/cluster.py, tests/unit/test_resultset.py
This commit provides a fix to the situation when iterating on a
ResultSet, the driver aborts the iteration if the server returns
an empty page even if there are next pages available.
Python driver is affected by the same problem as JAVA-2934
This fix is similar to https://github.com/datastax/java-driver/pull/1544
=> ResultSet: handle empty non-final pages on ResultSet iteration

cassandra/io/asyncioreactor.py
Short-term goal is to address the underlying issue at play in https://github.com/datastax/python-driver/pull/1118.  Longer-term this has the nice benefit of making us more compatible with how asyncio appears to be going generally.
=> PYTHON-1290 Convert asyncio reactor away from @asyncio.coroutine

cassandra/concurrent.py
Adds one more keyword argument `execution_profile` to the
`execute_concurrent` method to pass an execution profile. It is fowarded
to `Session.execute_async` call.
=> Add support for execution profiles in execute_concurrent.

cassandra/cluster.py, cassandra/util.py
=> Fix typos detected by Lintian during the packaging In Debian

tests/unit/test_policies.py
The AttributeError message for a missing property setter changed in [bpo-46730](https://bugs.python.org/issue46730).
=> Python 3.11 support [bpo-46730]

cassandra/io/asyncorereactor.py
If log is somehow gone and file exception due to the race mention in PYTHON-1266 it will also inevitably fail for the same reason after the loop so we need to catch the exception there as well.
I have hit it in some Cassandra dtest:
```
Exception in thread asyncore_cassandra_driver_event_loop (most likely raised during interpreter shutdown):
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
File "/usr/lib/python2.7/threading.py", line 754, in run
File "/dse/dse-db/bin/../lib/cassandra-driver-internal-only-3.25.0.zip/cassandra-driver-3.25.0/cassandra/io/asyncorereactor.py", line 262, in _run_loop
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'debug'
```
[PYTHON-1266]: …
=> Handle "log gone" (PYTHON-1266) at the end of _run_loop

tests/integration/__init__.py, tests/integration/standard/test_single_interface.py
Reproduced the test failure locally; the change described here causes the test to then pass
=> PYTHON-1329 Change expected port numbers if use_single_interface is used

tests/integration/cqlengine/management/test_compaction_settings.py, tests/integration/cqlengine/management/test_management.py, tests/integration/cqlengine/model/test_class_construction.py, tests/integration/cqlengine/test_batch_query.py, tests/integration/long/test_ipv6.py, tests/integration/simulacron/test_connection.py, tests/integration/standard/test_authentication.py, tests/integration/standard/test_client_warnings.py, tests/integration/standard/test_cluster.py, tests/integration/standard/test_metadata.py, tests/integration/standard/test_single_interface.py, tests/integration/standard/test_types.py, tests/unit/advanced/test_graph.py, tests/unit/cqlengine/test_connection.py, tests/unit/test_connection.py, tests/unit/test_control_connection.py, tests/unit/test_policies.py, tests/unit/test_protocol.py, tests/unit/test_response_future.py, tests/unit/test_timestamps.py
The deprecated aliases were removed in Python 3.11 in python/cpython#28268 .
=> Refactor deprecated unittest aliases for Python 3.11 compatibility.

docs/column_encryption.rst
Looks like I wasn't following rst as closely as I should've been.
Relevant notes on code block formatting can be found [here](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#directives).
=> Fix for rendering of code blocks in CLE documentation

cassandra/cluster.py, cassandra/connection.py, cassandra/cqlengine/functions.py, cassandra/cqltypes.py, cassandra/protocol.py, cassandra/util.py
unit it tests ran successfully (with pytest) except for those related to PYTHON-1300.
============================================================= short test summary info ==============================================================
FAILED tests/unit/test_host_connection_pool.py::_PoolTests::test_borrow_and_return - TypeError: 'NoneType' object is not callable
FAILED tests/unit/test_host_connection_pool.py::_PoolTests::test_failed_wait_for_connection - TypeError: 'NoneType' object is not callable
FAILED tests/unit/test_host_connection_pool.py::_PoolTests::test_return_closed_connection - TypeError: 'NoneType' object is not callable
FAILED tests/unit/test_host_connection_pool.py::_PoolTests::test_return_defunct_connection - TypeError: 'NoneType' object is not callable
FAILED …
=> remove unnecessary import __future__

cassandra/cluster.py, cassandra/cqlengine/query.py, cassandra/datastax/graph/fluent/__init__.py, cassandra/query.py, docs/api/cassandra/cqlengine/models.rst, docs/cqlengine/connections.rst, docs/cqlengine/models.rst, docs/execution_profiles.rst, docs/faq.rst, docs/getting_started.rst, docs/graph_fluent.rst, docs/object_mapper.rst
docs: convert print statement to print function in docs and comments
so that the examples also run in python 3+ environments
follow-up of https://github.com/datastax/python-driver/pull/1009
=> docs: convert print statement to function in docs

cassandra/cqltypes.py
Let's say you have an object:
```
class Address(object):
def __init__(self, street, zipcode, **kwargs):
self.street = street
self.zipcode = zipcode
cluster.register_user_type('mykeyspace', 'address', Address)
```
And let's say the type actually contains another field, let's call i raw_address
Then inserting data through a prepared statement will actually fail : the driver will complain raw_address is missing.
This change addresses that, as any field should be optional.
=> Don't fail when inserting UDTs with prepared queries with some missing fields #224

Jenkinsfile
Updating Jenkinsfile to reflect recent supported Python versions.  Also trying to get nightlies going again against master.
=> Jenkinsfile cleanup

docs/column_encryption.rst
Version for 3.27.0 docs.  To be committed _before_ 3.28.0 is cut.
=> CONN-38 Notes for 3.27.0 on PYTHON-1350

docs/column_encryption.rst
Version for 3.28.0 docs. To be committed _after_ 3.28.0 is cut.
=> CONN-38 Notes for 3.28.0 on PYTHON-1350

Jenkinsfile
Requires Python 3.12.0 to be added to the Jenkins runners; don't merge until that's done.
=> Add Jenkins support for Python 3.12.0

cassandra/io/asyncioreactor.py
Other methods in asyncio module do still require an event loop as a param.
test_asyncioreactor.py passes locally with these changes.
=> PYTHON-1313 Fix asyncio removals in Python 3.10

docs/api/cassandra/cluster.rst
Fix a typo in the `add_callbacks` method signature.
=> docs: Fix typo in add_callbacks

cassandra/__init__.py, cassandra/cluster.py, cassandra/io/asyncorereactor.py, cassandra/io/libevreactor.py, tests/__init__.py, tests/integration/standard/test_connection.py
Goal is to maintain existing behaviour for Python 3.8 through 3.11.  For Python 3.12 return a specific exception type with a message indicating that asyncore won't work on Python 3.12 due to it's removal.
We also change the load process for the libs to use a reduce op.  We'll try to load working event loops in a specific sequence; if we're able to load one we short-circuit the rest, otherwise we keep trying.  Return a single exception which contains the full set of failures for loading each event loop implementation.
=> PYTHON-1366 Handle removal of asyncore in Python 3.12

setup.py
Documentation [here](https://python-driver.readthedocs.io/en/stable/installation.html#libev-support) mentions to install `libev` from homebrew. 
```sh
$ brew install libev
```
The problem I found is that the pre-build package from pip doesn't have the extensions compiled [PYTHON-1376](https://datastax-oss.atlassian.net/jira/software/c/projects/PYTHON/issues/PYTHON-1376). Building from source on macOS doesn't find `libev` include folder for Homebrew as well.
This PR fixes the missing include folder to be aligned with the current documentation.
[PYTHON-1376]: https://datastax-oss.atlassian.net/browse/PYTHON-1376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix build from source on macos using homebrew

setup.py
Need to make sure we can find include directories for packages installed on the Docker images used by cibuildwheel
=> PYTHON-1378 Expand search directories for includes

cassandra/numpy_parser.pyx
Reported also in https://datastax-oss.atlassian.net/browse/PYTHON-1359, minimal `example.py`:
```python
from cassandra.cluster import Cluster
from cassandra.query import tuple_factory
from cassandra.protocol import NumpyProtocolHandler
import pandas as pd
cluster = Cluster()
session = cluster.connect()
session.row_factory = tuple_factory
session.client_protocol_handler = NumpyProtocolHandler
print(pd.DataFrame(session.execute("SELECT broadcast_port FROM system.local").one()))
```
Result with numpy<1.24.0:
```
$ python3 example.py
broadcast_port
0            7000
```
Result with numpy>=1.24.0:
```
$ python3 example.py
/usr/lib/python3/dist-packages/cassandra/io/libevreactor.py:370: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have …
```
=> PYTHON-1359 Fix for numpy>=1.24.0

tests/unit/test_response_future.py
The legacy unittest class method assertRaisesRegexp was deprecated in favour of assertRaisesRegex
=> Replace deprecated method assertRaisesRegexp for assertRaisesRegex

Jenkinsfile
Fix for unexpected test issues after recent Jenkins upgrade forced us to move to Java11 as the default for all runners
=> Explicitly select Java8 via Jabba before running integration tests

tests/integration/cqlengine/management/test_management.py, tests/integration/standard/test_metadata.py
I've confirmed via local testing that both integration tests fail with Python 3.12 before any changes (something we've already observed in Jenkins).  Also confirmed that both integration tests also pass using Python 3.8 after this change.
=> PYTHON-1384: Remove usages of unittest.assertDictContainsSubset

cassandra/cqlengine/functions.py, cassandra/util.py, examples/request_init_listener.py, ez_setup.py, setup.py, tests/integration/advanced/graph/__init__.py, tests/integration/long/utils.py
Removed unnecessary future print_function, division, and with and some pre 3.0 handling
Does not touch __future__imports!
=> Removed future print_function, division, and with_statement and some pre 3.7 handling

cassandra/cqlengine/connection.py, cassandra/cqlengine/query.py
Prevent error logs on program startup:
```
/python/path/lib/python3.12/site-packages/cassandra/cqlengine/connection.py:318: SyntaxWarning: invalid escape sequence '\*'
```
These will turn into SyntaxErrors in future python versions. Source: https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences
> Changed in version 3.12: Unrecognized escape sequences produce a [SyntaxWarning](https://docs.python.org/3/library/exceptions.html#SyntaxWarning). In a future Python version they will be eventually a [SyntaxError](https://docs.python.org/3/library/exceptions.html#SyntaxError).
=> Use raw strings in some docstrings to avoid SyntaxWarning in Python 3.12 .

cassandra/cqlengine/columns.py, cassandra/query.py, cassandra/util.py, tests/integration/cqlengine/columns/test_validation.py, tests/integration/cqlengine/model/test_model_io.py, tests/integration/cqlengine/model/test_udts.py, tests/unit/cython/types_testhelper.pyx, tests/unit/test_types.py
before this change, when testing with cqlsh, we have warnings like:
```
<frozen importlib._bootstrap>:488: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
````
in this change, we replace the deprecated API with timezone-aware API, to avoid this warning.
=> cassandra/query: use timezone specific API to avoid deprecated warning

cassandra/cqltypes.py
It was part of https://github.com/datastax/python-driver/pull/1161.
Looks like some excessive debug code that was overlooked by @absurdfarce
=> Remove a leftover code

setup.py, test-requirements.txt, tox.ini
Upgrade cython to 3.x which builds for Python 3.x by default.
=> Upgraded cython to 3.0.x

tests/integration/__init__.py, tests/integration/advanced/__init__.py, tests/integration/advanced/graph/test_graph_query.py, tests/integration/advanced/test_auth.py, tests/integration/advanced/test_cont_paging.py, tests/integration/advanced/test_geometry.py, tests/integration/advanced/test_spark.py, tests/integration/cloud/conftest.py, tests/integration/cloud/test_cloud_schema.py, tests/integration/conftest.py, tests/integration/cqlengine/test_connections.py, tests/integration/cqlengine/test_ifexists.py, tests/integration/cqlengine/test_ifnotexists.py, tests/integration/cqlengine/test_lwt_conditional.py, tests/integration/cqlengine/test_timestamp.py, tests/integration/cqlengine/test_ttl.py, tests/integration/standard/column_encryption/test_policies.py, tests/integration/standard/test_concurrent.py, tests/integration/standard/test_custom_payload.py, tests/integration/standard/test_custom_protocol_handler.py, tests/integration/standard/test_cython_protocol_handlers.py, tests/integration/util.py, tests/unit/test_concurrent.py, tests/unit/test_policies.py, tests/unit/test_protocol.py, tests/unit/test_segment.py, tests/unit/test_types.py, tests/unit/test_util_types.py, tests/util.py
This PR addresses spelling issues in test code. PyCharm's spell checker was used to flag issues needed correction.
=> Fixing spelling and minor whitespace issues in tests

tests/integration/__init__.py, tests/integration/cqlengine/statements/test_base_statement.py
SASI indexes have been removed in DSE 6.9.0.
Error message: `Column 'text' has a SASI index but SASI is not supported anymore. This index should removed and probably replaced by an equivalent Storage Attached Index (SAI)`
=> PYTHON-1402 Run integration tests with DSE 6.9.0

cassandra/cluster.py, cassandra/concurrent.py, tests/unit/test_concurrent.py
This makes these functions infinitely more discoverable for someone (correctly) looking at the Session class for ways to throw data into Cassandra
=> add execute_concurrent_async and expose execute_concurrent_* in Session

README.rst, cassandra/cluster.py, cassandra/io/libevreactor.py, docs/object_mapper.rst
The recent pruning of extraneous branches wound up preventing many of the links in our docs from working due to the removal of datastax.github.io/python-driver.  The goal here is to replace all those URLs with direct references into the DataStax documentation, at least for now.
Also cleaned up a few other things while I was here:
* Removed references to long-gone DataStax Community
* Fixed the Travis badges on the front-end README.rst
=> Documentation cleanup
