- cassandra/cqltypes.py
- cassandra/metadata.py
Builds on #234 
Properly unhexlify encoded names
Fix issue with _build_usertype
> PYTHON-208 - UserType issues in Python 3

- cassandra/cluster.py
- cassandra/io/eventletreactor.py
- docs/api/cassandra/io/eventletreactor.rst
- docs/api/index.rst
- setup.py
- tests/__init__.py
- tests/integration/standard/test_connection.py
- tests/unit/io/test_asyncorereactor.py
> PYTHON-194 - Eventlet reactor/connection

- cassandra/cluster.py
- cassandra/io/eventletreactor.py
- setup.py
- tests/integration/standard/test_connection.py
Apache licensed, from MagnetoDB project
https://github.com/stackforge/magnetodb/blob/master/magnetodb/common/cassandra/io/eventletreactor.py
> Add eventlet reactor

- test-requirements.txt
- tests/integration/datatype_utils.py
- tests/integration/standard/test_metrics.py
- tests/integration/standard/test_types.py
- tests/integration/standard/test_udts.py
These fixes most of the issues with the integration tests.
> Merge in Jenkins stablizations

- tests/integration/__init__.py
Fixes up issues in the ipv6 tests, and also clean-remove CCM clusters so they don't interfere with succeeding tests.
> Fixed IPv6 tests, and streamlined cluster removal

- tests/integration/long/test_consistency.py
- tests/integration/long/test_loadbalancingpolicies.py
- tests/integration/long/utils.py
Fixes issues in LoadBalancingPolicyTests.
> Catch OperationTimedOut exception, removed sleeps

- test-requirements.txt
- tests/integration/standard/test_metadata.py
Enables twisted unit tests, and fixes two typos in TestCodeCoverage
> Enable twisted tests

- cassandra/metadata.py
- tests/integration/standard/test_metadata.py
> PYTHON-241 - Meta indexes for Index Meta

- cassandra/metadata.py
This is the suggested change for https://datastax-oss.atlassian.net/browse/PYTHON-241.
> CASSANDRA-7814: Added indexes to table and ks metadata 

- tests/integration/long/test_large_data.py
- tests/integration/long/test_schema.py
- tests/integration/standard/test_query.py
Fixes issues in:
LargeDataTests
SchemaTests
LightweightTransactionTests
> Fix more jenkins tests

- tests/integration/standard/test_metadata.py
Handle OperationTimedOut in SchemaMetadataTests in TearDown.
> Handle OperationTimedOut in SchemaMetadataTests in TearDown

- tests/integration/standard/test_cluster.py
> [PYTHON-206] connect timeout tests

- tests/integration/cqlengine/model/test_model_io.py
- tests/integration/cqlengine/model/test_udts.py
> [PYTHON-246] tests for float/double updates in cqlengine

- tests/integration/standard/test_query.py
Added validation for for client ip tracing in the integration tests.
> Adding tests for PYTHON-235

- tests/integration/long/test_large_data.py
Some of the wide row tests didn't have very good validation, and they were timing out during inserts in jenkins. This should remedy those problems.
> Adding validation and fixing timeouts for wide-row integration tests.

- cassandra/cluster.py
- cassandra/connection.py
- cassandra/io/asyncorereactor.py
- cassandra/io/eventletreactor.py
- cassandra/io/geventreactor.py
- cassandra/io/libevreactor.py
- cassandra/io/libevwrapper.c
- cassandra/io/twistedreactor.py
- cassandra/query.py
- docs/object_mapper.rst
- tests/unit/test_connection.py
- tests/unit/test_response_future.py
> PYTHON-108 - Timers

- tests/integration/__init__.py
Fixed typo in test harness detecting C* versions
> Fix typo in test harness detecting C* versions

- tests/integration/standard/test_metadata.py
Unbreak UDF metadata tests, running them only if native protocol v 4+
> Unbreak UDF metadata tests, run only if protocol v 4+

- tests/integration/__init__.py
- tests/integration/long/test_custom_payload.py
- tests/integration/standard/test_query.py
- tox.ini
Tests cases for python-280 and formatting cleanup
> Python 280 test

- cassandra/cqlengine/management.py
- cassandra/cqlengine/models.py
- tests/integration/cqlengine/model/test_model.py
> PYTHON-244 - cqle: Protect ks/cf identifiers that use keywords

- cassandra/cqlengine/columns.py
- cassandra/cqltypes.py
- cassandra/protocol.py
- tests/unit/test_marshalling.py
- tests/unit/test_types.py
> Type corrections and updated unit test

- tests/integration/cqlengine/model/test_model.py
> [PYTHON-244] Update docs for test

- tests/integration/standard/test_cluster.py
- tests/integration/standard/test_metadata.py
[PYTHON-291] Tests for refresh schema metadata
> [PYTHON-291] Tests for refresh schema metadata

- cassandra/cluster.py
- docs/api/cassandra/cluster.rst
> PYTHON-304 - Add documentation for connection pool settings

- cassandra/cluster.py
> PYTHON-305 - Warn when UDT registered, but protocol_version < 3

- tests/integration/standard/test_prepared_statements.py
Test for automatic repreparation error
> [PYTHON-207] Test for automatic repreparation error

- tests/unit/test_policies.py
> Test infinite max attempts for ConstantReconnectionPolicy

- tests/integration/long/test_loadbalancingpolicies.py
Test for default loadbalancing policy
> [PYTHON-160] Test for default loadbalancing policy

- tests/integration/cqlengine/model/test_model_io.py
- tests/integration/cqlengine/model/test_udts.py
Tests for Date, Time, SmallInt, TinyInt in cqlengine
> [PYTHON-245] Tests for Date, Time, SmallInt, TinyInt in cqlengine

- tests/integration/cqlengine/columns/test_container_columns.py
- tests/integration/cqlengine/model/test_udts.py
- tests/integration/standard/test_types.py
> Jenkins stabilization fixes

- cassandra/metadata.py
- docs/api/cassandra/metadata.rst
- tests/unit/test_metadata.py
> Update CQL keywords, expose in API docs.

- cassandra/protocol.py
https://issues.apache.org/jira/browse/CASSANDRA-9515
> PYTHON-329 - Update custom payload value encoding for CASSADNRA-9515

- tests/integration/__init__.py
- tests/integration/cqlengine/__init__.py
- tests/integration/cqlengine/columns/test_validation.py
- tests/integration/cqlengine/model/test_udts.py
- tests/integration/cqlengine/query/test_queryset.py
- tests/integration/long/test_consistency.py
- tests/integration/long/test_failure_types.py
- tests/integration/long/test_ipv6.py
- tests/integration/long/test_loadbalancingpolicies.py
- tests/integration/long/test_schema.py
- tests/integration/long/utils.py
- tests/integration/standard/test_cluster.py
- tests/integration/standard/test_concurrent.py
- tests/integration/standard/test_metadata.py
- tests/integration/standard/test_metrics.py
- tests/integration/standard/test_query.py
- tests/integration/standard/test_types.py
- tests/integration/standard/test_udts.py
- tests/stress_tests/test_load.py
- tests/stress_tests/test_multi_inserts.py
- tests/unit/io/test_asyncorereactor.py
- tests/unit/io/test_libevreactor.py
- tests/unit/test_time_util.py
Windows tests suppport and stabilization
> Windows tests suppport and stabilization

- tests/integration/cqlengine/columns/test_validation.py
- tests/integration/cqlengine/management/test_management.py
- tests/integration/cqlengine/model/test_model_io.py
- tests/integration/cqlengine/model/test_udts.py
- tests/integration/cqlengine/query/test_queryset.py
Cqlengine fixes to skip tests properly
> Cqlengine fixes to skip tests properly

- tests/integration/long/test_ssl.py
Retry cluster connection in SSL test
> [PYTHON-322] Retry cluster connection in SSL test

- tests/integration/long/test_failure_types.py
- tests/integration/long/test_ssl.py
- tests/integration/standard/test_cluster.py
- tests/integration/standard/test_metadata.py
more fixes for jenkins test stabilization
> more fixes for jenkins test stabilization

- tests/integration/standard/test_types.py
- tests/integration/standard/test_udts.py
A few more test stabilizations
> A few more test stabilizations

- tests/__init__.py
- tests/integration/long/test_failure_types.py
- tests/unit/io/eventlet_utils.py
- tests/unit/io/gevent_utils.py
- tests/unit/io/test_asyncorereactor.py
- tests/unit/io/test_eventletreactor.py
- tests/unit/io/test_geventreactor.py
- tests/unit/io/test_libevreactor.py
- tests/unit/io/test_libevtimer.py
- tests/unit/io/test_twistedreactor.py
- tests/unit/io/utils.py
- tox.ini
Unit/Integration tests for python 108.
Added improvements infrastructure changes for various reactor tests going forward. 
Cleaned up tox dependencies.
> Python 108 Test

- .gitignore
- .travis.yml
- cassandra/marshal.py
- setup.py
- tests/integration/cqlengine/query/test_batch_query.py
- tests/integration/cqlengine/query/test_queryset.py
- tests/integration/standard/test_client_warnings.py
- tests/integration/standard/test_custom_payload.py
- tests/integration/standard/test_udts.py
- tox.ini
Plus many other test improvements.
> 342 - optionally cythonize core driver files

- .gitignore
- .travis.yml
- cassandra/marshal.py
- cassandra/murmur3.c
- setup.py
- test-requirements.txt
- tests/integration/cqlengine/query/test_batch_query.py
- tests/integration/cqlengine/query/test_queryset.py
- tests/integration/standard/test_client_warnings.py
- tests/integration/standard/test_custom_payload.py
- tests/integration/standard/test_udts.py
- tests/unit/io/test_twistedreactor.py
- tox.ini
superset of #361
made against 2.7 instead of master
Based on #364 -- review/merge 364 first for simplified diff
> PYTHON-357 - enable murmur3 for PyPy runtimes

- cassandra/metadata.py
- tests/integration/standard/test_metadata.py
Allows the driver to connect even if there is unexpected/inconsistent
schema metadata.
> PYTHON-370 - Contain and log schema metadata parsing exceptions.

- build.yaml
- tests/integration/standard/test_metadata.py
Adding yaml for job builder. 
I added a workaround for failures involving schema disagreement in the metadata tests.
> Adding yaml for job builder automation

- cassandra/cqltypes.py
- cassandra/metadata.py
> PYTHON-402 clustering order from table meta

- tests/integration/standard/test_metadata.py
Tests for materialized view metadata
> [PYTHON-371] Tests for materialized view metadata

- cassandra/metadata.py
> PYTHON-399 - Add where_clause to system_schema.views

- cassandra/metadata.py
Do #400 first for simplified diff.
> PYTHON-399 - more complex select for MVs

- build.yaml
- tests/integration/__init__.py
- tests/integration/cqlengine/test_ttl.py
- tests/integration/standard/test_cluster.py
- tests/integration/standard/test_metadata.py
- tests/integration/standard/test_query.py
- tests/integration/standard/test_row_factories.py
Added a few tests to reproduce and test for the issues in python-419
> Adding tests for python-419

- cassandra/metadata.py
- docs/api/cassandra/metadata.rst
- tests/integration/standard/test_metadata.py
also includes some unrelated doc and test cleanup
> PYTHON-404 - unify IndexMetadata model API

- tests/integration/standard/test_metadata.py
Also changed schema metadata tests to use common setup/teardown.
> Added test for Python-402 

- cassandra/metadata.py
Also changing
Changing all_as_cql to internal method to avoid confusion
> Fixing issue with ; delimeter on as_cql_query for keyspace. 

- tests/integration/standard/test_metadata.py
Not sure if this has a ton of value, but I realized we didn't have a test for multiple indices on a single column. I figured i would validate that this worked appropriately.
> Adding test for multiple indicies metadata.

- .travis.yml
This should get us off the legacy infrastructure and onto the new container infrastructure. Everything seems to work great with these changes.
> Moving travis over to the new infrastructure

- cassandra/cqlengine/columns.py
- cassandra/cqlengine/models.py
- cassandra/cqlengine/usertype.py
- tests/integration/cqlengine/model/test_model_io.py
- tests/integration/cqlengine/query/test_named.py
> PYTHON-348 - previous value tracking in cqlengine

- build.yaml
- test-requirements.txt
- tests/integration/__init__.py
- tests/integration/cqlengine/__init__.py
- tests/integration/cqlengine/query/test_named.py
- tests/integration/cqlengine/test_consistency.py
- tests/integration/standard/test_cluster.py
- tests/integration/standard/test_custom_protocol_handler.py
- tests/integration/standard/test_cython_protocol_handlers.py
- tests/integration/standard/test_metadata.py
- tests/integration/standard/test_metrics.py
- tests/integration/standard/test_prepared_statements.py
Adding a skip where needed, fixing issue with cross test pollution in cqlengine.
> Fixes for test case issues.

- tests/integration/standard/test_metadata.py
Also added a little more validation. Probably not a big deal, but I wanted to make sure new metadata was reflected, rather then just checking to see if it was refreshed.
> Fixing issue where sessions can leak upon test failure.

- cassandra/cqltypes.py
Inner types are always serialized with v3 + encoding.
> PYTHON-215 - Properly serdes nested collections when proto < 3

- tests/integration/__init__.py
- tests/integration/cqlengine/query/test_named.py
- tests/integration/standard/test_cython_protocol_handlers.py
- tests/integration/standard/test_query.py
- tests/integration/standard/test_types.py
- tests/integration/standard/test_udts.py
Test additions for the 3.0.0 release.
Includes some refactoring work and misc test fixes.
> 3.0.0 test

- cassandra/deserializers.pyx
> cython: fix offset overflow in large collections

- tests/integration/__init__.py
Changes require in order for us to run our standard python test suite against a dse server using ccm.
> Enable python driver to run tests against dse clusters

- tests/integration/long/test_schema.py
Added simple testcase for testing schema_agreement addition
> Adding test case for python-458

- CHANGELOG.rst
- tests/integration/cqlengine/model/test_udts.py
This is the additional test for the issue mentioned in #467
> Add a test for updating UDT with nones

- cassandra/cqlengine/connection.py
* Avoid lazy_connect_lock race condition
> PYTHON-310: Add lazy_connect_lock to avoid race condition with multiple threads

- cassandra/cqlengine/operators.py
- cassandra/cqlengine/query.py
- docs/cqlengine/queryset.rst
- tests/integration/cqlengine/operators/test_where_operators.py
- tests/integration/cqlengine/query/test_queryset.py
I tried to keep this simple and followed what I'm seen in our current code. Perhaps, I didn't forget something else affected by a new operator. If so, let me know.
I indent to add the documentation tomorrow morning.
> PYTHON-258: Add CONTAINS operator for collections

- cassandra/cqlengine/columns.py
- cassandra/cqlengine/query.py
- tests/integration/cqlengine/columns/test_container_columns.py
This should have all of our changes squashed with master rebased. Please look it over see if I'm missing any vital tests cases or of I screwed up something when I rebased master in.
> Cqlengine tuple changes, and test cases

- CHANGELOG.rst
- cassandra/cluster.py
- cassandra/cqlengine/query.py
- docs/api/cassandra/cqlengine/models.rst
- docs/api/cassandra/cqlengine/query.rst
- tests/integration/cqlengine/test_ifnotexists.py
- tests/integration/cqlengine/test_transaction.py
- tests/unit/test_resultset.py
Superset of #343 and targeting 3.1 dev branch.
> PYTHON-336 - Expose LWT results in cqlengine LWTException

- tests/integration/cqlengine/columns/test_container_columns.py
> PYTHON-478 : Added tests for nested collections

- tests/integration/cqlengine/query/test_queryset.py
Modified existing tests to make sure 0 results work correctly, and exceptions are thrown on non-indexed collections.
PYTHON-258
> PYTHON-258  tests error and negative scenarios

- tests/integration/cqlengine/query/test_queryset.py
Also cleaning up the test suite to not use indexed collections with C*< 2.1
> PYTHON-266 : Adding checks for empty, and invalid distinct queries

- cassandra/deserializers.pyx
> optional Cython BytesType->bytearray deserializer

- tests/integration/cqlengine/query/test_queryset.py
Just added some variation to same theme. I wanted to make sure models with columns where some where db_fields and others weren't would be exercised as well.
> PYTHON-351 : Added documentation and slight model variation to  tests

- tests/integration/cqlengine/test_ifexists.py
Mostly just documentation, added two tests with multiple batch statements. To ensure LWTExceptions are throw appropriately.
Needed a new model type to allow for batch statements to use the same partition key.
>  PYTHON-432: Updating tests, and adding documentation for

- tests/integration/cqlengine/model/test_model_io.py
- tests/integration/cqlengine/query/test_updates.py
Added integration tests for python-475 updated to work with latest from master
> PYTHON-475 adding integration test

- cassandra/cluster.py
- cassandra/cqlengine/connection.py
- cassandra/cqlengine/query.py
- cassandra/cqlengine/statements.py
- tests/integration/cqlengine/query/test_queryset.py
- tests/integration/cqlengine/statements/test_base_statement.py
- tests/integration/cqlengine/statements/test_select_statement.py
> PYTHON-323: Add ability to set query's fetch_size and limit using ORM

- cassandra/deserializers.pyx
- tests/integration/standard/test_types.py
In addition to this simple test I also ran a regression with DesBytesTypeByteArray set as the default deserializer.It all passed. Given the usecase this should be sufficient.
> Simple test for Python-503, slight doc tweak

- cassandra/cqlengine/statements.py
done while analyzing PYTHON-256
> cqle: simplify conditional in MapUpdateClause

- tests/integration/__init__.py
- tests/integration/cqlengine/management/test_management.py
Maybe a bit overboard here, but I added some tests for both new logging messages.
> PYTHON-260 added test for additional logging

- cassandra/cqlengine/management.py
> PYTHON-533 - make sync_table work with indexes on collections, C* 3.0+

- cassandra/cluster.py
> PYTHON-444 - richer error for ResponseFuture timeout callback

- cassandra/cluster.py
- cassandra/metadata.py
- cassandra/policies.py
- docs/api/cassandra/cluster.rst
- docs/api/cassandra/policies.rst
> PYTHON-69 - AddressTranslator interface

- cassandra/cluster.py
- cassandra/pool.py
> PYTHON-332 - broadcast and listen addresses on Host

- CHANGELOG.rst
- cassandra/__init__.py
- cassandra/cqlengine/statements.py
- tests/integration/cqlengine/columns/test_counter_column.py
> PYTHON-547 - fix OM counter state management

- cassandra/policies.py
- tests/unit/test_policies.py
Resolve hosts in WhiteListRoundRobinPolicy
> PYTHON-565

- cassandra/metadata.py
- tests/integration/standard/test_metadata.py
As discussed on CASSANDRA-11055, this is one more fix for the 2.7.2-cassandra-2.1 branch.
> Fixed tests for some legacy thrift tables

- CONTRIBUTING.rst
> fixed typo in CONTRIBUTING.rst

- docs/cqlengine/third_party.rst
Added **kwargs because without you are getting an exception about unknown kwargs.
> cassandra_init() added **kwargs

- cassandra/connection.py
I noticed this while working on [CASSANDRA-11464](https://issues.apache.org/jira/browse/CASSANDRA-11464).
> Fix unsupported protocol version error message

- cassandra/cqlengine/columns.py
A small change but important for a 3rd party lib which uses these.
> Comparison operators for Columns

- cassandra/cluster.py
- cassandra/connection.py
- cassandra/protocol.py
- cassandra/query.py
- cassandra/row_parser.pyx
- tests/integration/standard/test_custom_protocol_handler.py
- tests/unit/test_connection.py
- tests/unit/test_parameter_binding.py
- tests/unit/test_response_future.py
>  PYTHON-71 - use prepared metadata and skip row result meta

- cassandra/cqlengine/query.py
- tests/integration/cqlengine/test_lwt_conditional.py
builds on #592, fixing broken non-conditional queries
> PYTHON-580 - cqlengine conditional handling for update delete phase

- tests/integration/cqlengine/query/test_queryset.py
> Removed an inconsistent sleep use in a test

- cassandra/cluster.py
> Don't omit ignored nodes from schema agreement, if they're up

- cassandra/cluster.py
not just any completed (possibly errored) attempt
>  PYTHON-617 - Wait for first *successful* connect on initial

- cassandra/__init__.py
- cassandra/cluster.py
- cassandra/connection.py
- cassandra/protocol.py
This is based on top of https://github.com/datastax/python-driver/pull/640.
> PYTHON-619 (v5 error code map)

- cassandra/metadata.py
This should keep the new metadata type query from blowing up in C* 2.0
> Fix to keep type queries from breaking metadata construction in C* <2.1

- cassandra/cluster.py
- cassandra/pool.py
> PYTHON-628 - fix race adding connection pool to session while handling keyspace change

- tests/integration/__init__.py
- tests/integration/standard/test_policies.py
Looking to make sure I didn't miss anything major here with regards to code paths.
> PYTHON-218 added test for speculative execution policies

- cassandra/__init__.py
Updating driver to 3.7.0 version
> 3.7.0 version

- cassandra/metadata.py
> Quote index name in cql string where necessary

- cassandra/metadata.py
- tests/integration/standard/test_metadata.py
> Add interfaces for defining and registering table extensions

- cassandra/metadata.py
- tests/integration/standard/test_metadata.py
> make table extensions for for views, too

- cassandra/policies.py
- tests/integration/long/test_loadbalancingpolicies.py
- tests/unit/test_policies.py
See [PYTHON-643](https://datastax-oss.atlassian.net/browse/PYTHON-643).
> add shuffle_replicas config option

- cassandra/timestamps.py
Addresses log over-generation discovered on Windows.
> set defaults for timestamp generator logging

- benchmarks/callback_full_pipeline.py
- cassandra/cluster.py
- cassandra/connection.py
- cassandra/deserializers.pyx
- cassandra/marshal.py
- cassandra/protocol.py
- cassandra/query.py
- cassandra/util.py
- docs/cqlengine/models.rst
- docs/security.rst
- tests/integration/standard/test_cluster.py
- tests/integration/standard/test_query.py
- tests/unit/io/test_twistedreactor.py
- tests/unit/test_connection.py
- tests/unit/test_parameter_binding.py
**NOTE**: This PR doesn't target `master`, it targets the branch for PR-705.
> Pr 705 suggestions

- requirements.txt
- setup.py
> update six dependency

- cassandra/cqlengine/columns.py
Tested UDT as well, works fine.
> PYTHON-750: Add Duration support to cqlengine

- cassandra/cluster.py
This addresses PYTHON-755, in which `_time_remaining` is updated incorrectly, by avoiding updating it at all.
> make _time_remaining a property

- cassandra/query.py
https://datastax-oss.atlassian.net/browse/PYTHON-626
> PYTHON-626: improve prepared stmt docs

- cassandra/connection.py
When use `python-driver` with latest `lz4` I got a lot of `DeprecationWarning`:
/usr/local/lib/python3.5/dist-packages/lz4/__init__.py:18: DeprecationWarning: Call to deprecated function or method compress (use lz4.block.compress instead).
def compress(*args, **kwargs):
/usr/local/lib/python3.5/dist-packages/lz4/__init__.py:22: DeprecationWarning: Call to deprecated function or method decompress (use lz4.block.decompress instead).
def decompress(*args, **kwargs):
> Fix DeprecationWarning when using lz4

- cassandra/connection.py
@bjmb finally addressing [this comment](https://github.com/datastax/python-driver/pull/786#discussion_r123321919), could you have a look?
> check new value, not old one

- docs/dates_and_times.rst
> PYTHON-717

- setup.py
Looks like this was tested here PYTHON-737
> Add python3.6 classifier in setup.py

- tests/integration/long/test_loadbalancingpolicies.py
- tests/integration/standard/test_policies.py
- tests/unit/test_policies.py
I added the changes in cassandra/policies.py to test it with the final version, I'll remove it before merging since it's in another PR @mambocab
> Added tests for PYTHON-761

- cassandra/policies.py
- docs/api/cassandra/policies.rst
Fixes docs for `HostFilterPolicy`.
> Fix hfp docs

- build.yaml
- cassandra/io/asyncorereactor.py
- tests/integration/__init__.py
- tests/integration/long/test_failure_types.py
- tests/integration/standard/test_connection.py
- tests/integration/standard/test_policies.py
- tests/unit/io/test_asyncorereactor.py
We should remove the changes from the build.yaml before merging this PR.
> Move calls to asyncore to the loop thread

- tests/integration/standard/test_query.py
This looks like a normal query test @mambocab, I'd leave it but I don't have strong feelings if we don't add it.
> Added a test around SELECT JSON

- .travis.yml
Adds a [`Dangerfile`](danger.systems). Don't merge with the commit containing app changes, that's just for testing the checker.
> Danger danger high voltage

- CHANGELOG.rst
- setup.py
- test-requirements.txt
> PYTHON-833: Bump Cython dependency version to 0.27

- CHANGELOG.rst
- cassandra/__init__.py
- cassandra/protocol.py
- docs/api/cassandra.rst
@josh-mckenzie I took the liberty of adding a changelog entry and PR-ing this. Could you have a quick look?
[PYTHON-837](https://datastax-oss.atlassian.net/browse/PYTHON-837), [CASSANDRA-12148](https://issues.apache.org/jira/browse/CASSANDRA-12148)
> add CDCWriteException

- tests/integration/__init__.py
- tests/integration/long/test_failure_types.py
This fixes some test failures; @bjmb can you review?
> fix 3.11 failures after CASSANDRA-10786

- CHANGELOG.rst
- cassandra/cluster.py
- cassandra/connection.py
- cassandra/protocol.py
> Add `NO_COMPACT` version to CQL protocol, patch for CASSANDRA-10857.

- tests/integration/standard/test_prepared_statements.py
> 851 suggestions

- docs/conf.py
- docs/themes/custom/static/custom.css_t
- docs/themes/custom/theme.conf
Ensure you have sphinx >=1.3 installed..
> Set alabaster as theme for documentation

- CHANGELOG.rst
- cassandra/cqlengine/concurrent.py
- cassandra/cqlengine/connection.py
- cassandra/cqlengine/models.py
- cassandra/cqlengine/query.py
- docs/api/cassandra/cqlengine/models.rst
- docs/api/cassandra/cqlengine/query.rst
- docs/cqlengine/queryset.rst
- docs/cqlengine/upgrade_guide.rst
- tests/integration/cqlengine/__init__.py
- tests/integration/cqlengine/management/test_management.py
- tests/integration/cqlengine/model/test_class_construction.py
- tests/integration/cqlengine/model/test_polymorphism.py
- tests/integration/cqlengine/query/test_batch_query.py
- tests/integration/cqlengine/query/test_queryset.py
- tests/integration/cqlengine/test_consistency.py
- tests/integration/cqlengine/test_ifexists.py
- tests/integration/cqlengine/test_ifnotexists.py
- tests/integration/cqlengine/test_lwt_conditional.py
- tests/integration/cqlengine/test_timestamp.py
- tests/integration/cqlengine/test_ttl.py
To tests:
* The new get_all method
* The new warning when we override sync model methods
* all async methods
> PYTHON-605: Asynchronous execution support in cqlengine

- CHANGELOG.rst
- cassandra/cqlengine/query.py
- docs/cqlengine/batches.rst
- docs/cqlengine/upgrade_guide.rst
To test: cqlengine counter batch_type?
> PYTHON-888: Remove cassandra.cqlengine.query.BatchType

- cassandra/metadata.py
Original discussion here: https://github.com/mambocab/python-driver/pull/1
> Python group keys by replica fixes

- docs.yaml
For compat with the new docs-building behavior.
> add new virtualenv docs-building logic

- build.yaml
- test-requirements.txt
A minimal "only run the long tests nightly" change.
> Python skip long

- cassandra/protocol.py
- tests/__init__.py
- tests/integration/standard/test_cluster.py
- tests/integration/standard/test_context.py
This currently fails... but will be fixed in PYTHON-954
> Add tests for customizing context

- CHANGELOG.rst
- cassandra/cluster.py
- cassandra/connection.py
- cassandra/cython_deps.py
- cassandra/protocol.py
- cassandra/row_parser.pyx
- tests/integration/standard/test_custom_protocol_handler.py
- tests/unit/test_protocol.py
Reverts datastax/python-driver#931
> Revert "PYTHON-956: Make protocol messages pluggable"

- cassandra/io/asyncorereactor.py
- cassandra/io/twistedreactor.py
- tests/integration/standard/test_connection.py
- tests/unit/io/test_asyncioreactor.py
Fixes to the event-loop-thread-checking mechanism to fix this test.
> Python fix master loop tests

- build.yaml
- tests/unit/io/test_asyncioreactor.py
> Use ubuntu/bionic64/python-driver bionic image on jenkins

- build.yaml
- tests/integration/__init__.py
The only failure we see in jenkins is fixed by https://github.com/riptano/job-creator/pull/168
> Add test-dse and mapped_cassandra_version support

- CHANGELOG.rst
- cassandra/metadata.py
- tests/integration/__init__.py
- tests/integration/standard/test_dse.py
Requires a rebase, but the tests have run clean: http://jenkins-devtools.datastax.lan/job/datastax.python-driver.python-1018_dse-smoke-tests-and-version-check-logic.commit_branches/5/
> PYTHON-1018 dse smoke tests and version check logic

- CHANGELOG.rst
- build.yaml
- tests/integration/long/test_loadbalancingpolicies.py
- tests/integration/long/utils.py
Fixes the failures that cropped up [in this Jenkins run](http://jenkins-devtools.datastax.lan/job/datastax.python-driver.master.weekly_asyncio/25/testReport/).
> Long python test dse failures

- README-dev.rst
> PYTHON-988 fix nosetests docs in README-dev

- CHANGELOG.rst
- cassandra/cluster.py
I'll want to squash before merging, but: simple change.
> Python 944 add profile name to warning

- CHANGELOG.rst
- cassandra/__init__.py
- cassandra/cluster.py
- cassandra/policies.py
- cassandra/query.py
- tests/integration/long/test_policies.py
- tests/unit/test_cluster.py
- tests/unit/test_policies.py
> PYTHON-1007: Serial consistency level is not used 

- CHANGELOG.rst
- docs/security.rst
This is ready for a first review. I am in discussion to with the docs team for the finalization of this PR based on some docs fixes and changes.
> PYTHON-740: Expand Driver SSL Documentation

- CHANGELOG.rst
- build.yaml
- cassandra/cluster.py
- cassandra/connection.py
- cassandra/io/asyncioreactor.py
- cassandra/io/asyncorereactor.py
- cassandra/io/eventletreactor.py
- cassandra/io/geventreactor.py
- cassandra/io/libevreactor.py
- cassandra/io/twistedreactor.py
- cassandra/metadata.py
- cassandra/policies.py
- cassandra/pool.py
- docs/api/cassandra/cluster.rst
- docs/api/cassandra/connection.rst
- docs/api/cassandra/metadata.rst
- tests/integration/simulacron/test_endpoint.py
- tests/integration/standard/test_cluster.py
- tests/integration/standard/test_connection.py
- tests/integration/standard/test_metadata.py
- tests/integration/standard/test_policies.py
- tests/unit/io/test_twistedreactor.py
- tests/unit/io/utils.py
- tests/unit/test_connection.py
- tests/unit/test_control_connection.py
- tests/unit/test_host_connection_pool.py
- tests/unit/test_policies.py
* Add Host.host_id metadata
* Add Host.broadcast_rpc_address metadata
* Abstract Host connection information, now uses connection.EndPoint
* Add Cluster.endpoint_factory
> PYTHON-1079: Abstract Host Connection information

- CHANGELOG.rst
- cassandra/metadata.py
- cassandra/util.py
- tests/unit/test_util_types.py
This will be removed when we remove the python2 support..
> PYTHON-1091: Improve version parsing to support a non-integer 4th component

- CHANGELOG.rst
- cassandra/cluster.py
- cassandra/compat.py
- cassandra/metadata.py
- cassandra/util.py
This is part of the python3.7 support ..
> PYTHON-1023: Future-proof Mapping imports

- CHANGELOG.rst
- cassandra/cluster.py
- tests/integration/__init__.py
- tests/integration/standard/test_authentication.py
- tests/integration/standard/test_authentication_misconfiguration.py
https://datastax-oss.atlassian.net/browse/PYTHON-1117
Would an additional test add any value here?
> [PYTHON-1117] Call ConnectionException with correct kwargs

- CHANGELOG.rst
- cassandra/util.py
- tests/unit/test_util_types.py
https://datastax-oss.atlassian.net/browse/PYTHON-1118
> Allow connecting to pre-release server versions (PYTHON-1118)

- cassandra/cluster.py
https://datastax-oss.atlassian.net/browse/PYTHON-1103
> [PYTHON-1103] Make Session._execution_profile_to_string standalone

- build.yaml
https://datastax-oss.atlassian.net/browse/PYTHON-1037
> [PYTHON-1037] Update test schedules so we're nicer on jenkins

- cassandra/io/asyncorereactor.py
> PYTHON-1228 Provide log wrapper to asyncore so it doesnt error

- tests/integration/__init__.py
- tests/integration/advanced/graph/test_graph.py
- tests/integration/advanced/test_unixsocketendpoint.py
- tests/integration/standard/test_query.py
Left a few things unfixed in the last merge
https://jenkins-drivers-old.build.dsinternal.org/view/python-driver/job/datastax.python-driver.python-fix-fixes.commit_branches/3/
> More test fixes

- cassandra/metadata.py
- docs/api/cassandra/metadata.rst
- tests/integration/long/test_loadbalancingpolicies.py
- tests/unit/test_metadata.py
> PYTHON-1207: transient replication support (phase 2)

- CHANGELOG.rst
- Jenkinsfile
- cassandra/util.py
- requirements.txt
- setup.py
- tests/unit/advanced/test_geometry.py
Also:
+ bump geomet dependency to 0.2.
> PYTHON-1237 PYTHON-1243: Make geomet an optional dependency at runtime

- .travis.yml
- tox.ini
These fixes were originally implemented by user @tbbharaj in https://github.com/datastax/python-driver/pull/1108.
Extracting them into their own PR since 1108 is still being worked and I'd very much like to benefit from this
work across _all_ PRs against python-driver.
Major thanks to @tbbharaj for the original work here.
> Fixes to the Travis build.
